import type { Metadata } from 'next';
import { notFound, redirect } from 'next/navigation';
import CopyMessageButton from './copy-message-button';
import PrintRFQButton from './print-rfq-button';
import { requirePermission } from '@/lib/server/admin-session';
import { requirePermissionOrRedirect } from '@/lib/server/admin-page-guard';
import { getRFQRequest, isRFQAdminBackendConfigured, RFQ_QUOTATION_STATUSES, RFQ_SALES_PRIORITIES, RFQ_STATUSES, updateQuoteCustomerVisibility, updateRFQQuotationDraft, updateRFQRequestWorkflow } from '@/lib/server/rfq-admin';

export const dynamic = 'force-dynamic'; export const revalidate = 0;
export const metadata: Metadata = { title: 'RFQ Command Center', robots: { index: false, follow: false } };
const stockClass=(s:string)=>({in_stock:'bg-emerald-100 text-emerald-700',low_stock:'bg-amber-100 text-amber-700',out_of_stock:'bg-red-100 text-red-700',backorder:'bg-purple-100 text-purple-700',unknown:'bg-slate-100 text-slate-700'}[s]||'bg-slate-100 text-slate-700');
const money=(v:number|null|undefined,c='EGP')=>v==null?'—':`${c} ${Number(v).toFixed(2)}`;

export default async function RFQDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const adminAccess = await requirePermissionOrRedirect('rfq:view'); if (!adminAccess) return <main className='section'><div className='container'><p className='rounded-lg border border-amber-200 bg-amber-50 p-3 text-amber-700'>Not authorized.</p></div></main>; const { id } = await params; if (!isRFQAdminBackendConfigured()) return <main className="section"><div className="container"><p className="rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">Supabase admin backend is not configured.</p></div></main>;
  const rfq = await getRFQRequest(id); if (!rfq) notFound();
  async function updateAction(formData: FormData) { 'use server'; await requirePermission('rfq:update'); const status = String(formData.get('status') || 'new'); const salesPriority = String(formData.get('sales_priority') || 'normal'); const nextFollowUpAt = String(formData.get('next_follow_up_at') || '').trim(); const internalNotes = String(formData.get('internal_notes') || '').trim(); if (!RFQ_STATUSES.includes(status as any)) throw new Error('Please select a valid status.'); if (!RFQ_SALES_PRIORITIES.includes(salesPriority as any)) throw new Error('Please select a valid sales priority.'); if (internalNotes.length > 2000) throw new Error('Internal notes must be 2000 characters or less.'); await updateRFQRequestWorkflow(id, { status: status as any, salesPriority: salesPriority as any, nextFollowUpAt: nextFollowUpAt || null, internalNotes: internalNotes || null }); redirect(`/admin/rfq/${id}`); }
  async function quotationAction(formData: FormData) { 'use server'; await requirePermission('quote:create'); const items=(rfq.rfq_request_items||[]).map((item:any)=>({id:item.id,quotedUnitPrice:formData.get(`quoted_unit_price_${item.id}`),quotedLineTotal:formData.get(`quoted_line_total_${item.id}`),quotedItemNotes:String(formData.get(`quoted_item_notes_${item.id}`)||'').trim()||null})); await updateRFQQuotationDraft(id,{quotationStatus:String(formData.get('quotation_status')||'not_started') as any,quotationCurrency:String(formData.get('quotation_currency')||'EGP'),quotationValidUntil:String(formData.get('quotation_valid_until')||'').trim()||null,quotationPaymentTerms:String(formData.get('quotation_payment_terms')||'').trim()||null,quotationDeliveryTerms:String(formData.get('quotation_delivery_terms')||'').trim()||null,quotationNotes:String(formData.get('quotation_notes')||'').trim()||null,quotationDiscountAmount:formData.get('quotation_discount_amount'),quotationTaxAmount:formData.get('quotation_tax_amount'),items}); redirect(`/admin/rfq/${id}`); }
  async function quoteVisibilityAction(formData: FormData) { 'use server'; await requirePermission('quote:publish'); await updateQuoteCustomerVisibility(id, { quoteCustomerVisible: formData.get('quote_customer_visible') === 'on', quotePublicMessage: String(formData.get('quote_public_message') || '').trim() || null }); redirect(`/admin/rfq/${id}`); }
  const subtotal=(rfq.rfq_request_items||[]).reduce((sum:number,item:any)=>sum+Number(item.quoted_line_total||0),0); const discount=Number(rfq.quotation_discount_amount||0); const tax=Number(rfq.quotation_tax_amount||0); const grandTotal=subtotal-discount+tax;
  return <main className="section"><div className="container space-y-5"><div className="flex items-center justify-between"><a href="/admin/rfq" className="text-sm font-semibold text-navy-900 underline">← Back to list</a><PrintRFQButton label="Print Quotation Draft"/></div>
    <h1 className="text-2xl font-semibold text-slate-900">RFQ Command Center · {rfq.request_code}</h1>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">Quotation Builder</h2><form action={quotationAction} className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><select name="quotation_status" defaultValue={rfq.quotation_status || 'not_started'} className="rounded-md border px-3 py-2 text-sm">{RFQ_QUOTATION_STATUSES.map((s)=><option key={s}>{s}</option>)}</select><input name="quotation_currency" defaultValue={rfq.quotation_currency || 'EGP'} maxLength={8} className="rounded-md border px-3 py-2 text-sm"/><input type="date" name="quotation_valid_until" defaultValue={rfq.quotation_valid_until || ''} className="rounded-md border px-3 py-2 text-sm"/></div><div className="grid gap-3 md:grid-cols-2"><textarea name="quotation_payment_terms" defaultValue={rfq.quotation_payment_terms||''} maxLength={1000} placeholder="Payment terms" className="rounded-md border px-3 py-2 text-sm"/><textarea name="quotation_delivery_terms" defaultValue={rfq.quotation_delivery_terms||''} maxLength={1000} placeholder="Delivery terms" className="rounded-md border px-3 py-2 text-sm"/></div><textarea name="quotation_notes" defaultValue={rfq.quotation_notes||''} maxLength={2000} placeholder="Admin quotation notes (not public)" className="w-full rounded-md border px-3 py-2 text-sm"/><div className="grid gap-3 md:grid-cols-2"><input type="number" min="0" step="0.01" name="quotation_discount_amount" defaultValue={rfq.quotation_discount_amount ?? ''} placeholder="Discount" className="rounded-md border px-3 py-2 text-sm"/><input type="number" min="0" step="0.01" name="quotation_tax_amount" defaultValue={rfq.quotation_tax_amount ?? ''} placeholder="Tax" className="rounded-md border px-3 py-2 text-sm"/></div>
      <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-slate-600"><th className="px-2 py-1">Item</th><th className="px-2 py-1">Qty/Unit</th><th className="px-2 py-1">Stock</th><th className="px-2 py-1">Unit price</th><th className="px-2 py-1">Line total</th><th className="px-2 py-1">Item note</th></tr></thead><tbody>{rfq.rfq_request_items?.map((item:any)=><tr key={item.id} className="border-t align-top"><td className="px-2 py-1">{item.name}</td><td className="px-2 py-1">{item.quantity ?? '—'} / {item.unit || '—'}</td><td className="px-2 py-1">{item.matched_product ? <span className={`rounded-full px-2 py-1 text-xs font-semibold ${stockClass(item.matched_product.stock_status)}`}>{item.matched_product.stock_status}</span> : '—'}</td><td className="px-2 py-1"><input type="number" min="0" step="0.01" name={`quoted_unit_price_${item.id}`} defaultValue={item.quoted_unit_price ?? ''} className="w-28 rounded border px-2 py-1"/></td><td className="px-2 py-1"><input type="number" min="0" step="0.01" name={`quoted_line_total_${item.id}`} defaultValue={item.quoted_line_total ?? ''} className="w-28 rounded border px-2 py-1"/></td><td className="px-2 py-1"><textarea name={`quoted_item_notes_${item.id}`} defaultValue={item.quoted_item_notes||''} maxLength={1000} className="w-48 rounded border px-2 py-1"/></td></tr>)}</tbody></table></div>
      <p className="text-sm font-semibold text-slate-700">Quotation Draft Totals · Subtotal: {money(subtotal, rfq.quotation_currency)} · Discount: {money(discount, rfq.quotation_currency)} · Tax: {money(tax, rfq.quotation_currency)} · Grand total: {money(grandTotal, rfq.quotation_currency)}</p>
      <button className="rounded-md bg-navy-900 px-4 py-2 text-sm font-semibold text-white">Save quotation draft</button></form></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-2 font-semibold">Customer Quote Visibility & Response</h2><p className="mb-3 rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800">Only publish when pricing, terms, and validity are ready for customer review.</p><form action={quoteVisibilityAction} className="space-y-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="quote_customer_visible" defaultChecked={Boolean(rfq.quote_customer_visible)} /> Quote visible to customer tracking</label><textarea name="quote_public_message" defaultValue={rfq.quote_public_message || ''} maxLength={1000} placeholder="Optional customer-facing message" className="w-full rounded border p-2 text-sm" /><button className="rounded bg-navy-900 px-3 py-2 text-sm font-semibold text-white">Save quote visibility</button></form><div className="mt-3 grid gap-1 text-sm"><p><b>Response status:</b> {rfq.quote_customer_response_status || 'no_response'}</p><p><b>Response notes:</b> {rfq.quote_customer_response_notes || '—'}</p><p><b>Responded at:</b> {rfq.quote_customer_responded_at ? new Date(rfq.quote_customer_responded_at).toLocaleString() : '—'}</p><p><b>Last viewed at:</b> {rfq.quote_customer_last_viewed_at ? new Date(rfq.quote_customer_last_viewed_at).toLocaleString() : '—'}</p></div></section>
    <section className="print:block hidden rounded-xl border border-slate-200 bg-white p-4 text-sm"><h2 className="text-lg font-semibold">HILTECH Quotation Draft</h2><p><b>Request code:</b> {rfq.request_code}</p><p><b>Customer:</b> {rfq.full_name} ({rfq.company_name || '—'})</p><p><b>Contact:</b> {rfq.phone} · {rfq.email}</p><p><b>Quotation status:</b> {rfq.quotation_status || 'not_started'}</p><p><b>Valid until:</b> {rfq.quotation_valid_until || '—'}</p><p><b>Payment terms:</b> {rfq.quotation_payment_terms || '—'}</p><p><b>Delivery terms:</b> {rfq.quotation_delivery_terms || '—'}</p><p className="mt-2 text-xs">Final pricing, availability, and delivery are subject to HILTECH confirmation.</p></section>
  </div></main>;
}
