import type { Metadata } from 'next';
import { notFound, redirect } from 'next/navigation';
import CopyMessageButton from './copy-message-button';
import PrintRFQButton from './print-rfq-button';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { getRFQRequest, isRFQAdminBackendConfigured, RFQ_SALES_PRIORITIES, RFQ_STATUSES, updateRFQRequestWorkflow } from '@/lib/server/rfq-admin';

export const dynamic = 'force-dynamic'; export const revalidate = 0;
export const metadata: Metadata = { title: 'RFQ Command Center', robots: { index: false, follow: false } };
const stockClass = (s: string) => ({ in_stock:'bg-emerald-100 text-emerald-700', low_stock:'bg-amber-100 text-amber-700', out_of_stock:'bg-red-100 text-red-700', backorder:'bg-purple-100 text-purple-700', unknown:'bg-slate-100 text-slate-700' }[s] || 'bg-slate-100 text-slate-700');

export default async function RFQDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdminSession(); const { id } = await params; if (!isRFQAdminBackendConfigured()) return <main className="section"><div className="container"><p className="rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">Supabase admin backend is not configured.</p></div></main>;
  const rfq = await getRFQRequest(id); if (!rfq) notFound();
  async function updateAction(formData: FormData) { 'use server'; await requireAdminSession(); const status = String(formData.get('status') || 'new'); const salesPriority = String(formData.get('sales_priority') || 'normal'); const nextFollowUpAt = String(formData.get('next_follow_up_at') || '').trim(); const internalNotes = String(formData.get('internal_notes') || '').trim(); if (!RFQ_STATUSES.includes(status as any)) throw new Error('Please select a valid status.'); if (!RFQ_SALES_PRIORITIES.includes(salesPriority as any)) throw new Error('Please select a valid sales priority.'); if (internalNotes.length > 2000) throw new Error('Internal notes must be 2000 characters or less.'); await updateRFQRequestWorkflow(id, { status: status as any, salesPriority: salesPriority as any, nextFollowUpAt: nextFollowUpAt || null, internalNotes: internalNotes || null }); redirect(`/admin/rfq/${id}`); }

  return <main className="section"><div className="container space-y-5"><div className="flex items-center justify-between"><a href="/admin/rfq" className="text-sm font-semibold text-navy-900 underline">← Back to list</a><PrintRFQButton /></div>
    <h1 className="text-2xl font-semibold text-slate-900">RFQ Command Center · {rfq.request_code}</h1>
    <div className="grid gap-4 md:grid-cols-2 text-sm"><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-semibold mb-2">Customer / Project</h2><ul className="space-y-1"><li><b>Status:</b> {rfq.status}</li><li><b>Company:</b> {rfq.company_name || '—'}</li><li><b>Name:</b> {rfq.full_name}</li><li><b>Phone:</b> {rfq.phone}</li><li><b>Email:</b> {rfq.email}</li><li><b>Project location:</b> {rfq.project_location || '—'}</li><li><b>Project notes:</b> {rfq.project_notes || '—'}</li><li><b>Source:</b> {rfq.source}</li></ul></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-semibold mb-2">Workflow / Metadata</h2><ul className="space-y-1"><li><b>Sales priority:</b> {rfq.sales_priority || 'normal'}</li><li><b>Urgency:</b> {rfq.urgency || '—'}</li><li><b>Created:</b> {new Date(rfq.created_at).toLocaleString()}</li><li><b>Updated:</b> {new Date(rfq.updated_at).toLocaleString()}</li><li><b>Next follow-up:</b> {rfq.next_follow_up_at ? new Date(rfq.next_follow_up_at).toLocaleString() : '—'}</li><li><b>Last admin action:</b> {rfq.last_admin_action_at ? new Date(rfq.last_admin_action_at).toLocaleString() : '—'}</li></ul></section></div>

    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-2 font-semibold">Requested items</h2><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-slate-600"><th className="px-2 py-1">Name</th><th className="px-2 py-1">Qty</th><th className="px-2 py-1">Unit</th><th className="px-2 py-1">Notes</th><th className="px-2 py-1">Inventory</th></tr></thead><tbody>{rfq.rfq_request_items?.map((item: any) => <tr key={item.id} className="border-t border-slate-100 align-top"><td className="px-2 py-1">{item.name}</td><td className="px-2 py-1">{item.quantity ?? '—'}</td><td className="px-2 py-1">{item.unit || '—'}</td><td className="px-2 py-1">{item.notes || '—'}</td><td className="px-2 py-1">{item.matched_product ? <div className="space-y-1"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${stockClass(item.matched_product.stock_status)}`}>{item.matched_product.stock_status}</span><div className="text-xs text-slate-600">Qty: {item.matched_product.stock_quantity ?? '—'} · Low threshold: {item.matched_product.low_stock_threshold ?? '—'}</div><div className="text-xs text-slate-600">Checked: {item.matched_product.last_stock_checked_at ? new Date(item.matched_product.last_stock_checked_at).toLocaleString() : '—'}</div></div> : <span className="text-xs text-slate-500">No matched product</span>}</td></tr>)}</tbody></table></div></section>

    <section className="print:block hidden rounded-xl border border-slate-200 bg-white p-4 text-sm"><h2 className="text-lg font-semibold">HILTECH RFQ Summary</h2><p><b>Request code:</b> {rfq.request_code}</p><p><b>Customer:</b> {rfq.full_name} ({rfq.company_name || '—'})</p><p><b>Contact:</b> {rfq.phone} · {rfq.email}</p><p><b>Date:</b> {new Date().toLocaleDateString()}</p><p><b>Notes:</b> {rfq.project_notes || '—'}</p><p className="mt-2 text-xs">Final price and availability are confirmed by HILTECH.</p></section>

    <form action={updateAction} className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">Update workflow</h2><div className="grid gap-3 md:grid-cols-2"><select name="status" defaultValue={rfq.status} className="rounded-md border border-slate-300 px-3 py-2 text-sm">{RFQ_STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}</select><select name="sales_priority" defaultValue={rfq.sales_priority || 'normal'} className="rounded-md border border-slate-300 px-3 py-2 text-sm">{RFQ_SALES_PRIORITIES.map((s) => <option key={s} value={s}>{s}</option>)}</select><input type="datetime-local" name="next_follow_up_at" defaultValue={rfq.next_follow_up_at ? new Date(rfq.next_follow_up_at).toISOString().slice(0,16) : ''} className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><textarea name="internal_notes" defaultValue={rfq.internal_notes || ''} maxLength={2000} placeholder="Internal notes (admin-only)" className="rounded-md border border-slate-300 px-3 py-2 text-sm md:col-span-2" /></div><button className="mt-3 rounded-md bg-navy-900 px-4 py-2 text-sm font-semibold text-white">Save</button></form>
    {rfq.whatsapp_message && <section className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><div className="mb-2 flex items-center justify-between"><h2 className="font-semibold">Stored WhatsApp message</h2><CopyMessageButton text={rfq.whatsapp_message} /></div><pre className="whitespace-pre-wrap rounded border border-slate-200 bg-slate-50 p-3 text-xs">{rfq.whatsapp_message}</pre></section>}
  </div></main>;
}
