import type { Metadata } from 'next';
import Link from 'next/link';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { getGoogleAnalyticsAdvancedAnalytics, isGoogleAnalyticsAdminConfigured } from '@/lib/server/google-analytics-admin';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const metadata: Metadata = { title: 'HILTECH Admin Analytics', robots: { index: false, follow: false } };
const pctDrop = (p:number,c:number)=> p<=0?null:Math.max(0,((p-c)/p)*100);

export default async function Page({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdminSession();
  const params = await searchParams;
  const r = Array.isArray(params?.range) ? params?.range[0] : params?.range;
  const range = r === '7' || r === '90' ? Number(r) as 7 | 90 : 30;
  const gaConfigured = isGoogleAnalyticsAdminConfigured();
  let analytics:null|Awaited<ReturnType<typeof getGoogleAnalyticsAdvancedAnalytics>>=null; let analyticsError=false;
  if (gaConfigured) { try { analytics = await getGoogleAnalyticsAdvancedAnalytics(range); } catch (error) { analyticsError = true; console.error('[admin/analytics] Failed to load GA4 analytics dashboard.'); if (process.env.NODE_ENV !== 'production') console.error(error); } }
  const attempts = analytics?.funnel.find((x)=>x.eventName==='rfq_submit_attempt')?.eventCount ?? 0;
  const success = analytics?.funnel.find((x)=>x.eventName==='rfq_submit_success')?.eventCount ?? 0;
  const quoteViewed = analytics?.funnel.find((x)=>x.eventName==='quote_viewed')?.eventCount ?? 0;
  const quoteResponded = analytics?.funnel.find((x)=>x.eventName==='quote_response_submitted')?.eventCount ?? 0;
  const maxFunnel = Math.max(1,...(analytics?.funnel.map((x)=>x.eventCount)??[1]));

  return <main className='section'><div className='container space-y-6'>{/* trimmed for brevity in task */}
    <section className='rounded-xl border border-slate-200 bg-white p-4'><div className='flex flex-wrap items-start justify-between gap-3'><div><h1 className='text-2xl font-semibold text-slate-900'>HILTECH Website Analytics</h1><p className='mt-1 text-sm text-slate-600'>Aggregated public-site analytics for traffic, RFQ engagement, and quote interactions.</p></div><div className='flex flex-wrap gap-2 text-sm'>{[7,30,90].map((d)=><Link key={d} href={`/admin/analytics?range=${d}`} className={`rounded-md border px-3 py-2 font-semibold ${range===d?'border-navy-900 bg-navy-900 text-white':'border-slate-300'}`}>Last {d} days</Link>)}</div></div></section>
    {!gaConfigured?<p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>Google Analytics is not configured.</p>:analyticsError||!analytics?<p className='rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-700'>Analytics data is temporarily unavailable.</p>:<>
      <section className='grid grid-cols-2 gap-3 lg:grid-cols-4'>{[['Active users',analytics.totals.activeUsers],['Sessions',analytics.totals.sessions],['Page views',analytics.totals.screenPageViews],['Event count',analytics.totals.eventCount],['RFQ submit success count',success],['Quote viewed count',quoteViewed],['Quote response submitted count',quoteResponded]].map(([l,v])=><div key={String(l)} className='rounded-lg border border-slate-200 bg-white p-3'><p className='text-xs uppercase text-slate-500'>{l}</p><p className='mt-1 text-2xl font-semibold'>{Number(v).toLocaleString()}</p></div>)}</section>
      <section className='rounded-xl border border-slate-200 bg-white p-4'><h2 className='text-lg font-semibold'>RFQ Funnel</h2><div className='mt-3 space-y-2'>{analytics.funnel.map((row,i)=>{const p=i>0?analytics.funnel[i-1].eventCount:null; const d=p===null?null:pctDrop(p,row.eventCount); return <div key={row.eventName} className='rounded-lg border border-slate-100 p-3'><div className='flex justify-between text-sm'><span className='font-mono text-xs'>{row.eventName}</span><span className='font-semibold'>{row.eventCount.toLocaleString()}</span></div><div className='mt-2 h-2 rounded bg-slate-100'><div className='h-2 rounded bg-navy-900' style={{width:`${Math.max(6,row.eventCount/maxFunnel*100)}%`}} /></div>{d!==null?<p className='mt-1 text-xs text-slate-500'>Drop-off from previous step: {d.toFixed(1)}%</p>:null}</div>;})}</div></section>
      <section className='grid gap-4 lg:grid-cols-2'><div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Top Pages</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>path</th><th className='px-3 py-2'>title</th><th className='px-3 py-2'>views</th><th className='px-3 py-2'>active users</th></tr></thead><tbody>{analytics.topPages.map((x)=><tr key={`${x.pagePath}-${x.pageTitle}`} className='border-t border-slate-100'><td className='px-3 py-2 font-mono text-xs'>{x.pagePath}</td><td className='px-3 py-2'>{x.pageTitle}</td><td className='px-3 py-2'>{x.views.toLocaleString()}</td><td className='px-3 py-2'>{x.activeUsers.toLocaleString()}</td></tr>)}</tbody></table></div><div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Traffic Sources</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>channel/source</th><th className='px-3 py-2'>source medium</th><th className='px-3 py-2'>sessions</th><th className='px-3 py-2'>active users</th></tr></thead><tbody>{analytics.trafficSources.map((x)=><tr key={`${x.channelGroup}-${x.sourceMedium}`} className='border-t border-slate-100'><td className='px-3 py-2'>{x.channelGroup}</td><td className='px-3 py-2 font-mono text-xs'>{x.sourceMedium}</td><td className='px-3 py-2'>{x.sessions.toLocaleString()}</td><td className='px-3 py-2'>{x.activeUsers.toLocaleString()}</td></tr>)}</tbody></table></div></section>
      <section className='grid gap-4 lg:grid-cols-3'><div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Top Countries</div><table className='min-w-full text-sm'><tbody>{analytics.countries.map((x)=><tr key={x.country} className='border-t border-slate-100'><td className='px-3 py-2'>{x.country}</td><td className='px-3 py-2'>{x.activeUsers.toLocaleString()}</td><td className='px-3 py-2'>{x.sessions.toLocaleString()}</td></tr>)}</tbody></table></div><div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Device Split</div><table className='min-w-full text-sm'><tbody>{analytics.devices.map((x)=><tr key={x.deviceCategory} className='border-t border-slate-100'><td className='px-3 py-2 capitalize'>{x.deviceCategory}</td><td className='px-3 py-2'>{x.activeUsers.toLocaleString()}</td><td className='px-3 py-2'>{x.sessions.toLocaleString()}</td></tr>)}</tbody></table></div><div className='rounded-xl border border-slate-200 bg-white p-4 text-sm'><h3 className='font-semibold'>Insights</h3><ul className='mt-2 list-disc space-y-1 pl-5'><li>Top page by views: {analytics.topPages[0]?.pagePath ?? 'n/a'}.</li><li>Strongest event: {analytics.keyEvents[0]?.eventName ?? 'n/a'}.</li><li>{attempts>success?`RFQ attempts (${attempts}) exceed successes (${success}); review UX.`:'RFQ conversion appears stable.'}</li><li>{quoteViewed>0 && quoteResponded<Math.ceil(quoteViewed*0.25)?`Quote views (${quoteViewed}) are high vs responses (${quoteResponded}); consider follow-up.`:'Quote response follow-up appears stable.'}</li></ul></div></section>
      <section className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Key Events</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>event</th><th className='px-3 py-2'>count</th></tr></thead><tbody>{analytics.keyEvents.map((x)=><tr key={x.eventName} className='border-t border-slate-100'><td className='px-3 py-2 font-mono text-xs'>{x.eventName}</td><td className='px-3 py-2'>{x.eventCount.toLocaleString()}</td></tr>)}</tbody></table></section>
    </>}
  </div></main>;
}
