export const arRFQMessages = {
  basketTitle: 'سلة طلب عرض السعر',
  projectDetails: 'بيانات المشروع',
  fullName: 'الاسم بالكامل',
  phoneNumber: 'رقم الهاتف',
  emailAddress: 'البريد الإلكتروني',
  companyName: 'اسم الشركة',
  projectLocation: 'موقع المشروع',
  projectNotes: 'ملاحظات المشروع',
  submitRFQ: 'إرسال طلب عرض السعر',
  submitting: 'جارٍ الإرسال...',
  emptyBasket: 'أضف عنصرًا واحدًا على الأقل قبل إرسال طلب عرض السعر.',
  browseProducts: 'تصفح المنتجات',
  contactHiltech: 'تواصل مع HILTECH',
  quantity: 'الكمية',
  remove: 'حذف',
  urgency: 'درجة الاستعجال',
  reference: 'رقم الطلب',
  copyReference: 'نسخ رقم الطلب',
  trackThisRFQ: 'تتبع هذا الطلب',
  sendViaWhatsappToo: 'إرساله عبر واتساب أيضًا',
  backToProducts: 'العودة إلى المنتجات',
  successTitle: 'تم إرسال طلب عرض السعر بنجاح',
  successBody: 'تم استلام طلبك بنجاح. احتفظ برقم الطلب لاستخدامه في التتبع أو التواصل.',
  finalQuotationNote: 'يتم تأكيد عرض السعر النهائي بعد مراجعة الطلب.',
  priceReference: 'السعر المرجعي',
  priceOnRequest: 'السعر عند الطلب',
  availabilityNote: 'يتم تأكيد التوفر أثناء مراجعة طلب عرض السعر',
  fullNameRequired: 'الاسم بالكامل مطلوب.',
  phoneRequired: 'رقم الهاتف مطلوب.',
  emailRequired: 'البريد الإلكتروني مطلوب.',
  invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح.',
  quantityError: 'يجب أن تكون الكمية بين 1 و9999.',
  submitError: 'تعذر إرسال طلب عرض السعر. يرجى المحاولة مرة أخرى أو التواصل معنا عبر واتساب.',
  fullNamePlaceholder: 'اكتب الاسم بالكامل',
  phonePlaceholder: 'مثال: 01555357807',
  emailPlaceholder: 'name@example.com',
  companyPlaceholder: 'اسم الشركة اختياري',
  locationPlaceholder: 'المدينة أو موقع المشروع',
  notesPlaceholder: 'اكتب أي تفاصيل عن نطاق العمل أو الكميات أو المواعيد المطلوبة',
} as const;

export type RFQMessages = typeof arRFQMessages;
