export const arRFQMessages = {
  pageTitle: 'طلب عرض سعر للمشروع',
  pageSubtitle: 'راجع المنتجات المختارة، أضف الكميات وبيانات المشروع، ثم أرسل الطلب ليتابع فريق HILTECH التسعير والتواصل معك.',
  step1: '1. راجع العناصر',
  step2: '2. أضف بيانات المشروع',
  step3: '3. أرسل وتابع الطلب',
  itemsCardTitle: 'العناصر المختارة',
  projectDetails: 'بيانات المشروع',
  fullName: 'الاسم بالكامل',
  phoneNumber: 'رقم الهاتف',
  emailAddress: 'البريد الإلكتروني',
  companyName: 'اسم الشركة',
  projectLocation: 'موقع المشروع',
  projectNotes: 'ملاحظات المشروع',
  submitSectionTitle: 'إرسال طلب عرض السعر',
  submitRFQ: 'إرسال طلب عرض السعر',
  submitting: 'جارٍ الإرسال...',
  emptyBasket: 'سلة طلب العرض فارغة. أضف منتجات أولًا لتجهيز طلب عرض سعر منظم.',
  browseProducts: 'تصفح المنتجات',
  contactHelper: 'تحتاج مساعدة في تجهيز الطلب؟',
  contactHiltech: 'تواصل مع HILTECH',
  emptyStateTitle: 'سلة طلب العرض فارغة',
  emptyStateBody: 'أضف منتجات لإرسال طلب عرض سعر تفصيلي، أو أرسل نطاق المشروع يدويًا من الخيار التالي.',
  projectOnlyTitle: 'لا توجد قائمة منتجات بعد؟',
  projectOnlyBody: 'يمكنك إرسال نطاق المشروع يدويًا وسيقوم فريقنا بمساعدتك في تجهيز الـ BOQ المناسب.',
  sendProjectOnly: 'إرسال طلب مشروع فقط',
  addItemsToSubmit: 'أضف منتجًا واحدًا على الأقل لتفعيل إرسال الطلب.',
  quantity: 'الكمية',
  remove: 'حذف',
  urgency: 'درجة الاستعجال',
  reference: 'رقم المرجع',
  copyReference: 'نسخ رقم الطلب',
  trackThisRFQ: 'تتبع هذا الطلب',
  sendViaWhatsappToo: 'إرساله عبر واتساب أيضًا',
  backToProducts: 'العودة إلى المنتجات',
  successTitle: 'تم إرسال طلب عرض السعر بنجاح',
  successBody: 'احتفظ برقم المرجع لتتبع حالة الطلب لاحقًا.',
  finalQuotationNote: 'يتم تأكيد عرض السعر النهائي بعد مراجعة الطلب.',
  priceReference: 'السعر المرجعي',
  priceOnRequest: 'السعر عند الطلب',
  availabilityNote: 'يتم تأكيد التوفر أثناء مراجعة طلب عرض السعر',
  fullNameRequired: 'الاسم بالكامل مطلوب.',
  phoneRequired: 'رقم الهاتف مطلوب.',
  emailRequired: 'البريد الإلكتروني مطلوب.',
  invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح.',
  sendViaWhatsapp: 'إرسال عبر واتساب',
  quantityError: 'يجب أن تكون الكمية بين 1 و9999.',
  submitError: 'تعذر إرسال طلب عرض السعر. يرجى المحاولة مرة أخرى أو التواصل معنا عبر واتساب.',
  serverValidationPrefix: 'يرجى مراجعة التالي:',
  prepareHint: 'لتسريع التسعير، أضف موقع المشروع والكميات ونطاق الراك أو الفايبر أو CCTV وأي BOQ أو ملاحظات متاحة.',
  nextTitle: 'ماذا يحدث بعد الإرسال؟',
  nextPoint1: 'يراجع فريق HILTECH المنتجات والكميات وملاحظات المشروع.',
  nextPoint2: 'يتم تأكيد التوفر والبدائل المناسبة عند الحاجة.',
  nextPoint3: 'قد يتم التواصل معك عبر الهاتف أو واتساب لتوضيح التفاصيل.',
  nextPoint4: 'يمكنك متابعة حالة الطلب باستخدام رقم المرجع.',
  scopeCompletion: 'اكتمال النطاق',
  requiredItemsCovered: 'عناصر مطلوبة مغطاة',
  missingFromScope: 'ناقص من هذا النطاق',
  addRecommendation: 'أضف التوصية',
  scopeComplete: 'النطاق مكتمل',
  fullNamePlaceholder: 'اكتب الاسم بالكامل',
  phonePlaceholder: 'مثال: 01555357807',
  emailPlaceholder: 'name@example.com',
  companyPlaceholder: 'اسم الشركة اختياري',
  locationPlaceholder: 'المدينة أو موقع المشروع',
  notesPlaceholder: 'اكتب أي تفاصيل عن نطاق العمل أو الكميات أو المواعيد المطلوبة',
} as const;

export type RFQMessages = typeof arRFQMessages;
