import type { Metadata } from 'next';
import Link from 'next/link';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { getAdminDashboardSummary, isAdminDashboardBackendConfigured } from '@/lib/server/admin-dashboard';
import { getGoogleAnalyticsDashboardSummary, isGoogleAnalyticsAdminConfigured } from '@/lib/server/google-analytics-admin';
import AdminShell from '@/components/admin/AdminShell';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const metadata: Metadata = { title: 'HILTECH Admin Dashboard', robots: { index: false, follow: false } };

const badgeClass = 'rounded-full px-2 py-1 text-xs font-semibold bg-slate-100 text-slate-700';

export default async function AdminExecutiveDashboardPage() {
  await requireAdminSession();

  if (!isAdminDashboardBackendConfigured()) {
    return <main className="section"><div className="container"><h1 className="text-2xl font-semibold">HILTECH Admin Dashboard</h1><p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">Admin backend not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.</p></div></main>;
  }

  const data = await getAdminDashboardSummary();

  const gaConfigured = isGoogleAnalyticsAdminConfigured();
  let analyticsSummary: Awaited<ReturnType<typeof getGoogleAnalyticsDashboardSummary>> | null = null;
  let analyticsError = false;

  if (gaConfigured) {
    try {
      analyticsSummary = await getGoogleAnalyticsDashboardSummary();
    } catch (error) {
      analyticsError = true;
      console.error('[admin] Failed to load GA4 analytics summary.');
      if (process.env.NODE_ENV !== 'production') console.error(error);
    }
  }

  return <AdminShell title="HILTECH Admin Dashboard" description="Operational overview for RFQs, quotations, follow-ups, and product inventory." actions={<><Link href="/admin/rfq" className="rounded-md bg-navy-900 px-3 py-2 text-sm font-semibold text-white">View RFQs</Link><Link href="/admin/products" className="rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold">Product Admin</Link></>}>


    <section><h2 className='mb-2 text-lg font-semibold'>Command Center</h2><div className='grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4'>{[['Action Center','Follow-ups, quotes, inventory, and RFQ actions that need attention.','/admin/actions'],['Sales Dashboard','Revenue and RFQ pipeline performance.','/admin/sales'],['Website Analytics','Public website traffic and engagement.','/admin/analytics'],['Product Analytics','Demand and product performance.','/admin/products/analytics'],['RFQ Management','RFQ workflow and quotations.','/admin/rfq'],['Product Admin','Catalog and inventory management.','/admin/products'],['Import / Export','CSV tools for product operations.','/admin/products/import-export'],['Add Product','Create a new product record.','/admin/products/new']].map(([label,description,href])=><Link key={String(href)} href={String(href)} className='rounded-lg border border-slate-200 bg-white p-4 hover:bg-slate-50'><p className='text-sm font-semibold'>{label}</p><p className='mt-1 text-xs text-slate-600'>{description}</p></Link>)}</div></section>

    <section><h2 className='mb-2 text-lg font-semibold'>Today&apos;s Actions</h2><div className='grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5'>{[['Follow-ups due', data.workflowCounts.follow_up_due, '/admin/rfq?quick=followup_due'],['Quotation ready', data.quotationCounts.ready, '/admin/rfq?quick=quotation_ready'],['Urgent RFQs', data.workflowCounts.urgent, '/admin/rfq?quick=urgent'],['High-value RFQs', data.workflowCounts.high_value, '/admin/rfq?quick=high_value'],['Waiting customer', data.workflowCounts.waiting_customer, '/admin/rfq?quick=waiting_customer'],['Waiting supplier', data.workflowCounts.waiting_supplier, '/admin/rfq?quick=waiting_supplier'],['Low stock products', data.productCounts.low_stock, '/admin/products?stock_status=low_stock'],['Out of stock products', data.productCounts.out_of_stock, '/admin/products?stock_status=out_of_stock'],['Unknown stock products', data.productCounts.unknown, '/admin/products?stock_status=unknown']].map(([l,v,href])=> <Link key={String(l)} href={String(href)} className='rounded-lg border border-slate-200 bg-white p-3'><p className='text-xs uppercase text-slate-500'>{l}</p><p className='mt-1 text-2xl font-semibold'>{Number(v)}</p></Link>)}</div></section>

    <section className='space-y-3'><h2 className='text-lg font-semibold'>Website Analytics</h2>{!gaConfigured?<p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>Google Analytics is not configured.</p>:analyticsError||!analyticsSummary?<p className='rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-700'>Analytics data is temporarily unavailable.</p>:<div className='space-y-4'>
      <div className='grid grid-cols-2 gap-3 md:grid-cols-4'>{[['Active users (7d)', analyticsSummary.totalsLast7Days.activeUsers], ['Sessions (7d)', analyticsSummary.totalsLast7Days.sessions], ['Page views (7d)', analyticsSummary.totalsLast7Days.screenPageViews], ['Event count (7d)', analyticsSummary.totalsLast7Days.eventCount]].map(([l,v]) => <div key={String(l)} className='rounded-lg border border-slate-200 bg-white p-3'><p className='text-xs uppercase text-slate-500'>{l}</p><p className='mt-1 text-2xl font-semibold'>{Number(v).toLocaleString()}</p></div>)}</div>
      <div className='grid gap-4 lg:grid-cols-2'>
        <div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Top Pages (30d)</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Path</th><th className='px-3 py-2'>Title</th><th className='px-3 py-2'>Views</th><th className='px-3 py-2'>Active users</th></tr></thead><tbody>{analyticsSummary.topPagesLast30Days.length===0?<tr><td className='px-3 py-3 text-slate-500' colSpan={4}>No page analytics data yet.</td></tr>:analyticsSummary.topPagesLast30Days.map((row)=><tr key={`${row.pagePath}-${row.pageTitle}`} className='border-t border-slate-100'><td className='px-3 py-2 font-mono text-xs'>{row.pagePath}</td><td className='px-3 py-2'>{row.pageTitle}</td><td className='px-3 py-2'>{row.views.toLocaleString()}</td><td className='px-3 py-2'>{row.activeUsers.toLocaleString()}</td></tr>)}</tbody></table></div>
        <div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b border-slate-100 px-3 py-2 text-sm font-semibold'>Key Events (30d)</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Event</th><th className='px-3 py-2'>Count</th></tr></thead><tbody>{analyticsSummary.keyEventsLast30Days.length===0?<tr><td className='px-3 py-3 text-slate-500' colSpan={2}>No key event data yet.</td></tr>:analyticsSummary.keyEventsLast30Days.map((row)=><tr key={row.eventName} className='border-t border-slate-100'><td className='px-3 py-2 font-mono text-xs'>{row.eventName}</td><td className='px-3 py-2'>{row.eventCount.toLocaleString()}</td></tr>)}</tbody></table></div>
      </div>
    </div>}</section>

    <section><h2 className="mb-2 text-lg font-semibold">RFQ Overview</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{[['Total RFQs', data.rfqCounts.total], ['New RFQs', data.rfqCounts.new], ['In review', data.rfqCounts.in_review], ['Quoted', data.rfqCounts.quoted], ['Waiting client', data.rfqCounts.waiting_client], ['Won', data.rfqCounts.won], ['Closed / Lost', data.rfqCounts.closed_lost]].map(([l,v]) => <div key={String(l)} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div></section>

    <section><h2 className="mb-2 text-lg font-semibold">Sales Workflow</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['Urgent RFQs', data.workflowCounts.urgent], ['High value RFQs', data.workflowCounts.high_value], ['Waiting customer', data.workflowCounts.waiting_customer], ['Waiting supplier', data.workflowCounts.waiting_supplier], ['Follow-up due', data.workflowCounts.follow_up_due]].map(([l,v]) => <div key={String(l)} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div></section>

    <section><h2 className="mb-2 text-lg font-semibold">Quotation Overview</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[['Not started', data.quotationCounts.not_started], ['Draft', data.quotationCounts.draft], ['Ready', data.quotationCounts.ready], ['Sent', data.quotationCounts.sent], ['Revised', data.quotationCounts.revised], ['Cancelled', data.quotationCounts.cancelled]].map(([l,v]) => <div key={String(l)} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div></section>

    <section><h2 className="mb-2 text-lg font-semibold">Inventory Overview</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[['Total products', data.productCounts.total], ['Active products', data.productCounts.active], ['Low stock', data.productCounts.low_stock], ['Out of stock', data.productCounts.out_of_stock], ['Backorder', data.productCounts.backorder], ['Unknown stock', data.productCounts.unknown]].map(([l,v]) => <div key={String(l)} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div></section>

    <section className='grid gap-4 md:grid-cols-2'><div className='rounded-xl border border-slate-200 bg-white p-4'><h3 className='font-semibold'>RFQ Quick Links</h3><div className='mt-3 flex flex-wrap gap-2 text-sm'>{[['New / Pending','/admin/rfq?quick=new_pending'],['Urgent','/admin/rfq?quick=urgent'],['High value','/admin/rfq?quick=high_value'],['Follow-up due','/admin/rfq?quick=followup_due'],['Quotation drafts','/admin/rfq?quick=quotation_drafts'],['Quotation ready','/admin/rfq?quick=quotation_ready']].map(([label,href])=><Link key={String(href)} href={String(href)} className='rounded border border-slate-300 px-2 py-1'>{label}</Link>)}</div></div><div className='rounded-xl border border-slate-200 bg-white p-4'><h3 className='font-semibold'>Product Quick Links</h3><div className='mt-3 flex flex-wrap gap-2 text-sm'>{[['Product Admin','/admin/products'],['Product Analytics','/admin/products/analytics'],['Product CSV Import / Export','/admin/products/import-export'],['Low stock','/admin/products?stock_status=low_stock'],['Out of stock','/admin/products?stock_status=out_of_stock'],['Backorder','/admin/products?stock_status=backorder']].map(([label,href])=><Link key={String(href)} href={String(href)} className='rounded border border-slate-300 px-2 py-1'>{label}</Link>)}</div></div></section>

    <section className='space-y-3'><h2 className='text-lg font-semibold'>Recent RFQs</h2>{data.recentRFQs.length===0?<p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>No RFQs yet.</p>:<div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Request</th><th className='px-3 py-2'>Customer / Company</th><th className='px-3 py-2'>Status</th><th className='px-3 py-2'>Priority</th><th className='px-3 py-2'>Quotation</th><th className='px-3 py-2'>Next follow-up</th><th className='px-3 py-2'>Created</th><th className='px-3 py-2'>Items</th><th className='px-3 py-2'>Action</th></tr></thead><tbody>{data.recentRFQs.map((row:any)=><tr key={row.id} className='border-t border-slate-100'><td className='px-3 py-2 font-semibold'>{row.request_code}</td><td className='px-3 py-2'>{row.full_name}<div className='text-xs text-slate-500'>{row.company_name||'—'}</div></td><td className='px-3 py-2'><span className={badgeClass}>{row.status}</span></td><td className='px-3 py-2'><span className={badgeClass}>{row.sales_priority||'normal'}</span></td><td className='px-3 py-2'><span className={badgeClass}>{row.quotation_status||'not_started'}</span></td><td className='px-3 py-2'>{row.next_follow_up_at ? new Date(row.next_follow_up_at).toLocaleString() : '—'}</td><td className='px-3 py-2'>{new Date(row.created_at).toLocaleString()}</td><td className='px-3 py-2'>{row.item_count}</td><td className='px-3 py-2'><Link className='font-semibold underline' href={`/admin/rfq/${row.id}`}>View details</Link></td></tr>)}</tbody></table></div>}</section>

    <section className='space-y-3'><h2 className='text-lg font-semibold'>Follow-up Due</h2>{data.followUpDueRFQs.length===0?<p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>No RFQs currently due for follow-up.</p>:<div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Request</th><th className='px-3 py-2'>Customer / Company</th><th className='px-3 py-2'>Priority</th><th className='px-3 py-2'>Next follow-up</th><th className='px-3 py-2'>Status</th><th className='px-3 py-2'>Action</th></tr></thead><tbody>{data.followUpDueRFQs.map((row:any)=><tr key={row.id} className='border-t border-slate-100'><td className='px-3 py-2 font-semibold'>{row.request_code}</td><td className='px-3 py-2'>{row.full_name}<div className='text-xs text-slate-500'>{row.company_name||'—'}</div></td><td className='px-3 py-2'><span className={badgeClass}>{row.sales_priority || 'normal'}</span></td><td className='px-3 py-2'>{row.next_follow_up_at ? new Date(row.next_follow_up_at).toLocaleString() : '—'}</td><td className='px-3 py-2'><span className={badgeClass}>{row.status}</span></td><td className='px-3 py-2'><Link href={`/admin/rfq/${row.id}`} className='font-semibold underline'>View details</Link></td></tr>)}</tbody></table></div>}</section>

    <section className='space-y-3'><h2 className='text-lg font-semibold'>Inventory Attention</h2>{data.inventoryAttentionProducts.length===0?<p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>No products currently need stock attention.</p>:<div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Code</th><th className='px-3 py-2'>Name</th><th className='px-3 py-2'>Category</th><th className='px-3 py-2'>Stock status</th><th className='px-3 py-2'>Stock qty</th><th className='px-3 py-2'>Low threshold</th><th className='px-3 py-2'>Action</th></tr></thead><tbody>{data.inventoryAttentionProducts.map((row:any)=><tr key={row.id} className='border-t border-slate-100'><td className='px-3 py-2 font-semibold'>{row.product_code}</td><td className='px-3 py-2'>{row.name}</td><td className='px-3 py-2'>{row.category||'—'}</td><td className='px-3 py-2'><span className={badgeClass}>{row.stock_status}</span></td><td className='px-3 py-2'>{row.stock_quantity ?? '—'}</td><td className='px-3 py-2'>{row.low_stock_threshold ?? '—'}</td><td className='px-3 py-2'><Link href={`/admin/products/${row.id}`} className='font-semibold underline'>Edit product</Link></td></tr>)}</tbody></table></div>}</section>
  </AdminShell>;
}
