import Link from 'next/link';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { getAdminProductAnalyticsData, isAdminProductAnalyticsBackendConfigured, parseProductAnalyticsRange } from '@/lib/server/admin-product-analytics';

function fmtMoney(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value || 0); }

export default async function AdminProductAnalyticsPage({ searchParams }: { searchParams: Promise<{ range?: string }> }) {
  await requireAdminSession();
  const params = await searchParams;
  const range = parseProductAnalyticsRange(params.range);

  if (!isAdminProductAnalyticsBackendConfigured()) {
    return <main className='section'><div className='container'><p className='rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600'>Product analytics backend is not configured.</p></div></main>;
  }

  let data: Awaited<ReturnType<typeof getAdminProductAnalyticsData>> | null = null;
  try { data = await getAdminProductAnalyticsData(range); } catch (error) { console.error('[admin/products/analytics] Failed to load product analytics data.'); if (process.env.NODE_ENV !== 'production') console.error(error); }
  if (!data) return <main className='section'><div className='container'><p className='rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-700'>Product analytics data is temporarily unavailable.</p></div></main>;

  return <main className='section'><div className='container space-y-5'>
    <div className='flex flex-wrap items-center justify-between gap-3'><div><h1 className='text-2xl font-semibold'>Product Analytics</h1><p className='text-sm text-slate-600'>Demand and inventory intelligence from Supabase RFQ and product operational data.</p></div><div className='flex flex-wrap gap-2'>{[7,30,90,365].map((r)=><Link key={r} href={`/admin/products/analytics?range=${r}`} className={`rounded border px-3 py-2 text-sm ${r===range?'bg-navy-900 text-white':'border-slate-300'}`}>{r}d</Link>)}</div></div>

    <section className='grid grid-cols-2 gap-3 lg:grid-cols-3'>
      {[
        ['Total requested items', data.kpis.totalRequestedItems],['Unique requested products/items', data.kpis.uniqueRequestedItems],['Unique requested categories', data.kpis.uniqueRequestedCategories],['RFQs with product demand', data.kpis.rfqsWithDemand],['Quoted product/item value', fmtMoney(data.kpis.quotedProductValue)],['Requested products with low stock', data.kpis.requestedLowStock],['Requested products out of stock/backorder', data.kpis.requestedOutBackorder],['Requested products with unknown stock', data.kpis.requestedUnknownStock],['Unmatched requested items', data.kpis.unmatchedRequestedItems],
      ].map(([l,v])=><div key={String(l)} className='rounded-lg border border-slate-200 bg-white p-3'><p className='text-xs uppercase text-slate-500'>{l}</p><p className='mt-1 text-xl font-semibold'>{String(v)}</p></div>)}
    </section>

    <section className='grid gap-4 lg:grid-cols-2'>
      <div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b px-3 py-2 text-sm font-semibold'>Top requested products/items</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Item</th><th className='px-3 py-2'>Category</th><th className='px-3 py-2'>Brand</th><th className='px-3 py-2'>Requests</th><th className='px-3 py-2'>Qty</th><th className='px-3 py-2'>Quoted value</th><th className='px-3 py-2'>Match</th></tr></thead><tbody>{data.topRequestedItems.map((r)=><tr key={r.key} className='border-t'><td className='px-3 py-2'>{r.name}</td><td className='px-3 py-2'>{r.category}</td><td className='px-3 py-2'>{r.brand || '—'}</td><td className='px-3 py-2'>{r.requestCount}</td><td className='px-3 py-2'>{r.totalQuantity}</td><td className='px-3 py-2'>{fmtMoney(r.quotedValue)}</td><td className='px-3 py-2'><span className={`rounded-full px-2 py-1 text-xs ${r.matched?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{r.matched?'Matched':'Unmatched'}</span></td></tr>)}</tbody></table></div>
      <div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b px-3 py-2 text-sm font-semibold'>Top requested categories</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Category</th><th className='px-3 py-2'>Requests</th><th className='px-3 py-2'>Qty</th><th className='px-3 py-2'>Quoted value</th></tr></thead><tbody>{data.topRequestedCategories.map((r)=><tr key={r.category} className='border-t'><td className='px-3 py-2'>{r.category}</td><td className='px-3 py-2'>{r.requestCount}</td><td className='px-3 py-2'>{r.totalQuantity}</td><td className='px-3 py-2'>{fmtMoney(r.quotedValue)}</td></tr>)}</tbody></table></div>
    </section>

    <section className='grid gap-4 lg:grid-cols-2'>
      <div className='rounded-xl border border-slate-200 bg-white p-4 text-sm'><h3 className='font-semibold'>Demand vs inventory insights</h3><ul className='mt-2 list-disc space-y-1 pl-5'><li>Most requested category is {data.insights.mostRequestedCategory}.</li><li>{data.insights.unknownStockDemanded} requested products have unknown stock.</li><li>{data.insights.outBackorderDemanded} demanded items are out of stock/backorder.</li><li>{data.insights.topQuotedDemand ? `Top quoted demand is ${data.insights.topQuotedDemand.name} with value ${fmtMoney(data.insights.topQuotedDemand.value)}.` : 'Top quoted demand is not available yet.'}</li>{data.insights.unmatchedExists?<li>Unmatched demand exists; consider linking RFQ items to product records.</li>:null}</ul></div>
      <div className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b px-3 py-2 text-sm font-semibold'>Top quoted products/categories by value</div><div className='grid gap-3 p-3 md:grid-cols-2'><div><p className='mb-2 text-xs font-semibold uppercase text-slate-500'>Products/items</p>{data.topQuotedProducts.length===0?<p className='text-sm text-slate-500'>No quoted line totals available for this range.</p>:<ul className='space-y-1 text-sm'>{data.topQuotedProducts.map((x)=> <li key={x.key}>{x.name} — {fmtMoney(x.quotedValue)}</li>)}</ul>}</div><div><p className='mb-2 text-xs font-semibold uppercase text-slate-500'>Categories</p>{data.topQuotedCategories.length===0?<p className='text-sm text-slate-500'>No category quoted values available for this range.</p>:<ul className='space-y-1 text-sm'>{data.topQuotedCategories.map((x)=> <li key={x.category}>{x.category} — {fmtMoney(x.quotedValue)}</li>)}</ul>}</div></div></div>
    </section>

    <section className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b px-3 py-2 text-sm font-semibold'>Inventory risk for demanded items</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Code</th><th className='px-3 py-2'>Name</th><th className='px-3 py-2'>Category</th><th className='px-3 py-2'>Stock status</th><th className='px-3 py-2'>Stock qty</th><th className='px-3 py-2'>Low threshold</th><th className='px-3 py-2'>Demand count</th><th className='px-3 py-2'>Quoted value</th><th className='px-3 py-2'>Action</th></tr></thead><tbody>{data.inventoryRisk.map((r)=><tr key={r.key} className='border-t'><td className='px-3 py-2'>{r.productCode || '—'}</td><td className='px-3 py-2'>{r.name}</td><td className='px-3 py-2'>{r.category}</td><td className='px-3 py-2'>{r.stockStatus}</td><td className='px-3 py-2'>{r.stockQuantity ?? '—'}</td><td className='px-3 py-2'>{r.lowStockThreshold ?? '—'}</td><td className='px-3 py-2'>{r.requestCount}</td><td className='px-3 py-2'>{fmtMoney(r.quotedValue)}</td><td className='px-3 py-2'>{r.matched ? <Link className='underline font-semibold' href={`/admin/products/${r.productId}`}>Edit product</Link> : '—'}</td></tr>)}</tbody></table></section>

    <section className='overflow-x-auto rounded-xl border border-slate-200 bg-white'><div className='border-b px-3 py-2 text-sm font-semibold'>Demand trend by day</div><table className='min-w-full text-sm'><thead className='bg-slate-50 text-left text-slate-600'><tr><th className='px-3 py-2'>Date</th><th className='px-3 py-2'>Requested items</th><th className='px-3 py-2'>RFQ count</th><th className='px-3 py-2'>Quoted value</th></tr></thead><tbody>{data.trends.map((t)=><tr key={t.date} className='border-t'><td className='px-3 py-2'>{t.date}</td><td className='px-3 py-2'>{t.requestedItemCount}</td><td className='px-3 py-2'>{t.rfqCount}</td><td className='px-3 py-2'>{fmtMoney(t.quotedValue)}</td></tr>)}</tbody></table></section>
  </div></main>;
}
