import type { ProductCategory } from './products';

export interface SolutionItem {
  slug: string;
  title: string;
  shortTitle: string;
  eyebrow: string;
  intro: string;
  problemStatement: string;
  solutionSummary: string;
  keyOutcomes: string[];
  deliveryScope: string[];
  typicalComponents: string[];
  implementationFlow: string[];
  relatedProductCategories: ProductCategory[];
  relatedProductIntelligenceSlugs: string[];
  rfqChecklist: string[];
  assuranceNotes: string[];
  disclaimer: string;
}

export const solutions: SolutionItem[] = [
  {
    slug: 'structured-cabling',
    title: 'Structured Cabling Solutions',
    shortTitle: 'Structured Cabling',
    eyebrow: 'Enterprise Access Layer',
    intro: 'Structured copper infrastructure for offices and commercial facilities with CAT6/CAT6A pathways, patching discipline, endpoint readiness, and testing-oriented handover.',
    problemStatement: 'Many projects face inconsistent endpoint quality, undocumented routes, and difficult troubleshooting when horizontal cabling is installed without a consistent technical framework.',
    solutionSummary: 'HILTECH supports structured cabling delivery through pathway planning, organized panel/outlet labeling, and coordinated installation workflows that can help reduce operational disruption depending on project scope.',
    keyOutcomes: ['Cleaner endpoint readiness across user areas', 'More maintainable panel-to-outlet documentation', 'Reduced rework risk through standards-based installation', 'Testing-oriented acceptance before handover'],
    deliveryScope: ['Site review and floor-wise endpoint planning', 'CAT6/CAT6A cable routing and termination support', 'Patch panel and outlet identification matrix', 'Test results package and handover documentation'],
    typicalComponents: ['CAT6/CAT6A cable', 'Patch panels', 'Keystone modules and faceplates', 'Copper patch cords', 'Cable management accessories'],
    implementationFlow: ['Requirement and route assessment', 'Cabling layout and bill of quantities alignment', 'Installation and termination sequencing', 'Testing, labeling, and issue closure', 'Documentation and handover review'],
    relatedProductCategories: ['Copper / CAT6 Cabling', 'Faceplates / Keystone / RJ45', 'Patch Cords & Connectivity'],
    relatedProductIntelligenceSlugs: ['copper-cat6-cabling', 'faceplates-keystone-rj45', 'patch-cords-connectivity'],
    rfqChecklist: ['Total endpoint count by area/floor', 'Preferred cabling standard (CAT6/CAT6A)', 'Patch panel density and rack locations', 'Required testing/reporting format', 'Project location and target timeline'],
    assuranceNotes: ['Scope can be adjusted for phased delivery.', 'Final quantities and route constraints are confirmed during project review.'],
    disclaimer: 'Final design, accessory mix, and availability remain subject to technical review and RFQ confirmation.'
  },
  {
    slug: 'fiber-backbone',
    title: 'Fiber Backbone Infrastructure',
    shortTitle: 'Fiber Backbone',
    eyebrow: 'Core & Distribution Connectivity',
    intro: 'Fiber backbone planning for building, floor, and data room interconnects using OM3/OS2 strategies, ODF readiness, and OTDR-oriented validation support.',
    problemStatement: 'Backbone links often underperform when route planning, termination strategy, and connector standards are not aligned across buildings and technical rooms.',
    solutionSummary: 'HILTECH can help structure fiber backbone projects with route mapping, ODF/termination planning, and test-oriented workflows that support stable interconnect performance.',
    keyOutcomes: ['Better backbone path visibility', 'Improved readiness for future capacity growth', 'Consistent LC/SC connectivity practices', 'Validation support before operational cutover'],
    deliveryScope: ['Route and endpoint alignment', 'Fiber termination and ODF readiness', 'Connector/interface mapping', 'OTDR and continuity test package support'],
    typicalComponents: ['OM3/OS2 fiber cable', 'ODF and splice accessories', 'LC/SC adapters and pigtails', 'Fiber patch cords', 'Protection and labeling materials'],
    implementationFlow: ['Backbone topology review', 'Route and termination planning', 'Installation and splicing workflow', 'OTDR-oriented testing and remediation', 'As-built and handover alignment'],
    relatedProductCategories: ['Fiber Optic Systems', 'Patch Cords & Connectivity', 'Cabinets / Racks / PDU'],
    relatedProductIntelligenceSlugs: ['fiber-optic-systems', 'patch-cords-connectivity', 'cabinets-racks-pdu'],
    rfqChecklist: ['Fiber type/core count by route', 'Approximate route distances and environment', 'Termination interface preference (LC/SC)', 'ODF/rack requirements', 'Project schedule and commissioning target'],
    assuranceNotes: ['Performance expectations depend on route conditions and active equipment compatibility.', 'Outdoor/indoor material selection is confirmed per site constraints.'],
    disclaimer: 'Technical compliance, product availability, and lead times are finalized after RFQ and site-specific validation.'
  },
  {
    slug: 'data-rooms', title: 'Data Room Infrastructure', shortTitle: 'Data Rooms', eyebrow: 'Technical Room Readiness', intro: 'Data room infrastructure covering rack/cabinet planning, PDU integration, ODF and patching arrangement, and maintainable cable management foundations.', problemStatement: 'Technical rooms can become difficult to scale and support when rack power, patching density, and cable organization are treated as separate tasks.', solutionSummary: 'HILTECH supports integrated data room preparation with practical coordination between rack layouts, in-rack power distribution, optical/copper patching, and maintainability goals.', keyOutcomes: ['Improved room organization and serviceability', 'Clearer rack-level power and patch planning', 'Better readiness for expansion and MAC operations', 'Stronger handover structure for operations teams'], deliveryScope: ['Room readiness and rack elevation planning', 'Cabinet, PDU, and accessory setup support', 'ODF/patching arrangement and labeling', 'Cable management and final documentation'], typicalComponents: ['Network cabinets and racks', 'PDUs and power accessories', 'ODFs and patch panels', 'Vertical/horizontal cable managers', 'Rack mounting and finishing accessories'], implementationFlow: ['Room requirement review', 'Rack/power/patching design alignment', 'Installation and organization execution', 'Validation, labeling, and snag closure', 'Handover pack and support notes'], relatedProductCategories: ['Cabinets / Racks / PDU', 'Cable Management / Duct Systems', 'Patch Cords & Connectivity'], relatedProductIntelligenceSlugs: ['cabinets-racks-pdu', 'cable-management-duct-systems', 'patch-cords-connectivity'], rfqChecklist: ['Room dimensions and rack unit targets', 'Power feed and PDU expectations', 'ODF/patch panel quantities', 'Cooling/access constraints', 'Expansion and timeline requirements'], assuranceNotes: ['Implementation scope can include staged room activation.', 'Power compatibility and safety requirements are confirmed with project stakeholders.'], disclaimer: 'Final scope, dimensions, and product models are confirmed during technical review and procurement alignment.' },
  {
    slug: 'cctv-infrastructure', title: 'CCTV Infrastructure Solutions', shortTitle: 'CCTV Infrastructure', eyebrow: 'Security Connectivity Layer', intro: 'Security infrastructure support for camera connectivity, control-room readiness, network paths, and PoE-aware planning in commercial and enterprise sites.', problemStatement: 'CCTV projects may face coverage and reliability issues when cabling routes, network segmentation, and power assumptions are not coordinated early.', solutionSummary: 'HILTECH can help prepare CCTV infrastructure with structured route planning, PoE-oriented connectivity guidance, and control-room technical readiness depending on project scope.', keyOutcomes: ['More consistent camera connectivity foundations', 'Improved control-room integration readiness', 'Reduced coordination gaps between power/network/security teams', 'Clearer expansion path for additional camera zones'], deliveryScope: ['Camera connectivity pathway planning', 'Security network patching and endpoint organization', 'Control-room rack/endpoint readiness', 'Testing and labeling support before handover'], typicalComponents: ['Structured camera cabling', 'Security patching accessories', 'PoE-compatible connectivity elements', 'Control-room rack/patch components', 'Route protection and containment'], implementationFlow: ['Site/security requirement capture', 'Pathway and network readiness planning', 'Cabling and control-room implementation', 'Validation and issue closure', 'Handover checklist and expansion notes'], relatedProductCategories: ['CCTV & Security', 'Copper / CAT6 Cabling', 'Cable Management / Duct Systems'], relatedProductIntelligenceSlugs: ['cctv-security', 'copper-cat6-cabling', 'cable-management-duct-systems'], rfqChecklist: ['Camera count and location schedule', 'PoE and switching assumptions', 'Control-room readiness requirements', 'Route constraints (indoor/outdoor)', 'Timeline and phased rollout details'], assuranceNotes: ['Final camera ecosystem choices are subject to compatibility confirmation.', 'Security topology requirements can vary by client policy and compliance context.'], disclaimer: 'Availability, compatibility, and final technical scope are confirmed during RFQ and project planning.' },
  {
    slug: 'network-testing', title: 'Network Testing & Validation', shortTitle: 'Testing & Validation', eyebrow: 'Commissioning Confidence', intro: 'Fluke/OTDR-oriented testing workflows that support acceptance, documentation readiness, and reduced future fault risk before infrastructure handover.', problemStatement: 'Without structured validation, projects can pass installation stages but still face latent faults, inconsistent performance, or unresolved documentation gaps.', solutionSummary: 'HILTECH supports testing-led commissioning workflows with defined checkpoints, remediation loops, and reporting formats to help teams validate infrastructure quality before go-live.', keyOutcomes: ['Higher confidence in infrastructure handover', 'Earlier detection of route/termination issues', 'Improved documentation quality for operations teams', 'Reduced future troubleshooting effort'], deliveryScope: ['Test plan alignment and acceptance criteria', 'Copper and fiber test execution support', 'Non-conformance tracking and closure guidance', 'Final reporting package preparation'], typicalComponents: ['Fluke-oriented copper test workflows', 'OTDR-oriented fiber validation workflows', 'Labeling and record matrices', 'Test report templates and summaries'], implementationFlow: ['Acceptance criteria definition', 'Pre-test inspection and baseline checks', 'Structured copper/fiber validation', 'Issue remediation and retesting', 'Final documentation and sign-off support'], relatedProductCategories: ['Fiber Optic Systems', 'Copper / CAT6 Cabling', 'Patch Cords & Connectivity'], relatedProductIntelligenceSlugs: ['fiber-optic-systems', 'copper-cat6-cabling', 'patch-cords-connectivity'], rfqChecklist: ['Project areas and link volumes to be tested', 'Target standard and acceptance thresholds', 'Required report format and handover deadline', 'Retest policy expectations', 'Site access and timeline details'], assuranceNotes: ['Testing scope depends on installed media, standards, and required acceptance criteria.', 'Final acceptance remains subject to client/project governance.'], disclaimer: 'Testing outcomes and recommendations are project-specific and confirmed against agreed technical criteria.' },
  {
    slug: 'project-supply-rfq', title: 'Project Supply & RFQ Solutions', shortTitle: 'Project Supply & RFQ', eyebrow: 'Procurement Readiness', intro: 'Project-based product supply support through BOQ/RFQ preparation, availability confirmation, compatibility checks, and structured procurement requests.', problemStatement: 'Procurement delays and mismatched components can affect deployment timelines when product requests lack technical detail or compatibility context.', solutionSummary: 'HILTECH supports RFQ-driven supply workflows that can help teams define quantities, align product direction, and confirm availability before final quotation depending on scope.', keyOutcomes: ['Clearer BOQ/RFQ structure for procurement teams', 'Reduced compatibility ambiguity before ordering', 'Better visibility on availability and substitution options', 'Faster transition from scope to quotation review'], deliveryScope: ['BOQ/RFQ structuring support', 'Category-based product alignment', 'Availability and lead-time confirmation workflows', 'Compatibility notes for mixed ecosystems'], typicalComponents: ['Fiber and copper cabling materials', 'Racks, PDUs, and technical room accessories', 'Patching and endpoint components', 'CCTV/security connectivity items', 'Containment and cable management items'], implementationFlow: ['Requirement capture and category mapping', 'BOQ normalization and quantity checks', 'Availability and compatibility review', 'Quotation alignment and clarification', 'RFQ finalization and submission workflow'], relatedProductCategories: ['Fiber Optic Systems', 'Copper / CAT6 Cabling', 'Cabinets / Racks / PDU'], relatedProductIntelligenceSlugs: ['fiber-optic-systems', 'copper-cat6-cabling', 'cabinets-racks-pdu'], rfqChecklist: ['Project scope summary and technical priorities', 'Preferred brands/categories (if any)', 'Quantities and delivery location', 'Timeline and phase breakdown', 'Any mandatory compatibility requirements'], assuranceNotes: ['Equivalent product direction may be proposed subject to availability.', 'Pricing and delivery windows are finalized during formal quotation.'], disclaimer: 'Final scope, availability, and pricing are always confirmed per project and RFQ review.' },
];

export const solutionsBySlug = Object.fromEntries(solutions.map((s) => [s.slug, s])) as Record<string, SolutionItem>;
