import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { site } from '@/content/site';

export const metadata: Metadata = {
  title: 'HILTECH | حلول الشبكات والفايبر وطلبات عروض الأسعار في مصر',
  description: 'توريد وتنفيذ واختبار حلول الشبكات والفايبر والراك للشركات في مصر، مع طلب عرض سعر وتتبع حالة الطلب.',
  alternates: { canonical: `${site.siteUrl}/ar`, languages: { en: `${site.siteUrl}/`, ar: `${site.siteUrl}/ar`, 'x-default': `${site.siteUrl}/` } },
};

const trustStrip = ['تنفيذ داخل مصر','كابلات شبكات منظمة','حلول فايبر','تجهيز الراك','اختبار قبل التسليم','تتبع طلب العرض','متابعة عبر واتساب'];

export default function ArabicHomePage() {
  const tags=['كابلات منظمة','فايبر / ODF','تجهيز الراك','اختبار قبل التسليم'];
  return (
    <main>
      <section className="section bg-gradient-to-br from-navy-900 via-[#0c1d33] to-slate-900 text-white"><div className="container grid gap-6 lg:grid-cols-[1.2fr_1fr]"><div><p className="public-eyebrow text-orange-300">حلول البنية التحتية للشبكات في مصر</p><h1 className="mt-3 text-3xl font-bold leading-tight md:text-5xl">حلول شبكات وفايبر وراك جاهزة للتنفيذ والتسعير</h1><p className="mt-4 text-sm text-slate-100 sm:text-base">تساعد HILTECH الشركات في مصر على تجهيز البنية التحتية للشبكات، من تحديد النطاق واختيار المنتجات إلى التنفيذ والاختبار وطلب عرض السعر.</p><div className="mt-5 flex flex-col gap-2.5 sm:flex-row sm:flex-wrap"><Link href="/ar/rfq" className="btn-primary w-full justify-center sm:w-auto">اطلب عرض سعر</Link><Link href="/ar/products-partners" className="btn-secondary w-full justify-center sm:w-auto">تصفح المنتجات</Link><Link href="/ar/work" className="btn-secondary w-full justify-center sm:w-auto">شاهد الأعمال الميدانية</Link></div></div><article className="public-card overflow-hidden border-white/15 bg-white/5 p-0"><div className="relative aspect-[16/10] w-full"><Image src="/rack-data-room.jpg" alt="إثبات ميداني" fill className="object-cover"/></div><div className="p-4"><p className="public-eyebrow text-orange-300">إثبات ميداني</p><ul className="mt-3 grid grid-cols-2 gap-2">{tags.map((tag)=><li key={tag} className="public-marker justify-center border-white/20 bg-white/10 text-white">{tag}</li>)}</ul></div></article></div></section>
      <section className="section-compact"><div className="container"><div className="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm"><ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{trustStrip.map((item)=><li key={item} className="public-marker justify-center text-center">{item}</li>)}</ul></div></div></section>
      <section className="section-compact"><div className="container"><h2 className="text-2xl font-bold text-navy-900">جهّز نطاق مشروع كامل</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['تجهيز شبكة مكتب',['كابلات CAT6','باتش بانل','فيس بليت','ملحقات الراك','الاختبار']],['تجهيز راك وغرفة بيانات',['راك','PDU','تنظيم الكابلات','باتش بانل','التسمية والاختبار']],['نطاق فايبر وODF',['كابل فايبر','ODF','باتش كورد','اللحام والاختبار']],['بنية تحتية للكاميرات',['نقاط شبكة','كابلات','تجهيز الراك','جاهزية الطاقة والشبكة']]].map(([title,items])=><article key={title as string} className="public-card p-4"><h3 className="font-semibold text-slate-900">{title as string}</h3><ul className="mt-2 space-y-1 text-sm text-slate-700">{(items as string[]).map((it)=><li key={it}>• {it}</li>)}</ul><Link href="/ar/rfq" className="mt-3 inline-flex text-sm font-semibold text-orange-700">ابدأ طلب عرض بهذا النطاق</Link></article>)}</div></div></section>
      <section className="section-compact"><div className="container"><article className="public-card bg-slate-50 p-5"><h2 className="text-2xl font-bold text-navy-900">مدخل المنتجات وطلب العرض</h2><p className="mt-2 text-slate-700">تصفح المنتجات وأضف عناصر المشروع إلى سلة طلب عرض سعر واحدة.</p><div className="mt-4 flex flex-col gap-2.5 sm:flex-row"><Link href="/ar/products-partners" className="btn-secondary w-full justify-center sm:w-auto">تصفح المنتجات</Link><Link href="/ar/rfq" className="btn-primary w-full justify-center sm:w-auto">اطلب عرض سعر</Link></div></article></div></section>
      <section className="section bg-slate-50"><div className="container"><h2 className="text-2xl font-bold text-navy-900">أعمال ميدانية قابلة للتسليم والصيانة</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{[['تجهيز الراك وغرف البيانات','تنظيم المسارات والتجهيز للتسليم','/rack-front-cabling.jpg'],['أعمال الفايبر / ODF','تنفيذ ضمن نطاق واضح قبل التسعير','/fiber-splicing-workbench.jpg'],['الكابلات المنظمة والاختبار','اختبار قبل التسليم ودعم الصيانة','/testing-otdr-device.jpg']].map(([title,note,img])=><article key={title as string} className="public-card overflow-hidden p-0"><div className="relative aspect-[16/10] w-full"><Image src={img as string} alt={title as string} fill className="object-cover"/></div><div className="p-4"><h3 className="font-semibold text-slate-900">{title as string}</h3><p className="mt-1 text-sm text-slate-700">{note as string}</p><Link href="/ar/work" className="mt-3 inline-flex text-sm font-semibold text-orange-700">شاهد نطاق الأعمال</Link></div></article>)}</div></div></section>
      <section className="section bg-navy-800 text-white"><div className="container"><h2 className="text-3xl font-bold">جاهز لتسعير مشروع البنية التحتية؟</h2><p className="mt-3 text-slate-100">أرسل المنتجات والكميات أو BOQ أو متطلبات الموقع، وسيقوم فريق HILTECH بمراجعة النطاق ومتابعة عرض السعر.</p><div className="mt-5 flex flex-col gap-2.5 sm:flex-row"><Link href="/ar/rfq" className="btn-primary w-full justify-center sm:w-auto">اطلب عرض سعر</Link><a href={site.contact.whatsappGeneralLink} className="btn-secondary w-full justify-center border-white/20 bg-white/10 text-white hover:bg-white/20 sm:w-auto">تواصل عبر واتساب</a></div></div></section>
    </main>
  );
}
