import type { Metadata } from 'next';
import Link from 'next/link';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { isProductsAdminBackendConfigured, listProductsAdmin } from '@/lib/server/products-admin';
import { PRODUCT_STOCK_STATUSES, type ProductStockStatus } from '@/lib/types/products';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const metadata: Metadata = { title: 'Product Admin', robots: { index: false, follow: false } };

export default async function AdminProductsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdminSession();
  const query = await searchParams;
  if (!isProductsAdminBackendConfigured()) return <main className="section"><div className="container"><h1 className="text-2xl font-semibold">Product Admin</h1><p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">Supabase admin backend is not configured.</p></div></main>;
  const rows = await listProductsAdmin({ search: query.search, status: query.status as any, category: query.category, brand: query.brand, stock_status: query.stock_status as ProductStockStatus });
  const categories = Array.from(new Set(rows.map((r) => r.category).filter(Boolean))).sort();
  const brands = Array.from(new Set(rows.map((r) => r.brand).filter(Boolean) as string[])).sort();
  const summary = { total: rows.length, active: rows.filter((r) => r.status === 'active').length, low_stock: rows.filter((r) => r.stock_status === 'low_stock').length, out_of_stock: rows.filter((r) => r.stock_status === 'out_of_stock').length, backorder: rows.filter((r) => r.stock_status === 'backorder').length, unknown: rows.filter((r) => r.stock_status === 'unknown').length };
  return <main className="section"><div className="container space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Product Admin</h1><Link href="/admin/rfq" className="text-sm underline">Back to RFQ Admin</Link></div><div className="flex gap-2"><Link href="/admin/products/new" className="rounded-md bg-navy-900 px-3 py-2 text-sm font-semibold text-white">Add Product</Link><form action="/api/admin/logout" method="post"><button className="rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold">Logout</button></form></div></div>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-6">{[['Total products', summary.total], ['Active', summary.active], ['Low stock', summary.low_stock], ['Out of stock', summary.out_of_stock], ['Backorder', summary.backorder], ['Unknown', summary.unknown]].map(([l,v]) => <div key={String(l)} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-2xl font-semibold">{v}</p></div>)}</div>
  <form method="get" className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-6"><input name="search" defaultValue={query.search || ''} placeholder="Search code/name/brand/category" className="rounded-md border border-slate-300 px-3 py-2 text-sm md:col-span-2"/><select name="status" defaultValue={query.status || ''} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option><option value="active">active</option><option value="hidden">hidden</option><option value="archived">archived</option></select><select name="stock_status" defaultValue={query.stock_status || ''} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">All stock</option>{PRODUCT_STOCK_STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}</select><select name="category" defaultValue={query.category || ''} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">All categories</option>{categories.map((c) => <option key={c} value={c}>{c}</option>)}</select><select name="brand" defaultValue={query.brand || ''} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">All brands</option>{brands.map((b) => <option key={b} value={b}>{b}</option>)}</select><button className="rounded-md bg-navy-900 px-3 py-2 text-sm font-semibold text-white md:col-span-6">Apply filters</button></form>
  {rows.length===0? <p className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm">No products found for current filters.</p>:<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-[1200px] text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-3 py-2">Code</th><th className="px-3 py-2">Name</th><th className="px-3 py-2">Category</th><th className="px-3 py-2">Brand</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Stock</th><th className="px-3 py-2">Stock qty</th><th className="px-3 py-2">Low threshold</th><th className="px-3 py-2">Updated</th><th className="px-3 py-2">Action</th></tr></thead><tbody>{rows.map((r)=><tr key={r.id} className="border-t border-slate-100"><td className="px-3 py-2 font-semibold">{r.product_code}</td><td className="px-3 py-2">{r.name}</td><td className="px-3 py-2">{r.category}</td><td className="px-3 py-2">{r.brand||'—'}</td><td className="px-3 py-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{r.status}</span></td><td className="px-3 py-2"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-800">{r.stock_status}</span></td><td className="px-3 py-2">{r.stock_quantity ?? '—'}</td><td className="px-3 py-2">{r.low_stock_threshold ?? '—'}</td><td className="px-3 py-2">{new Date(r.updated_at).toLocaleString()}</td><td className="px-3 py-2"><Link href={`/admin/products/${r.id}`} className="underline font-semibold">Edit</Link></td></tr>)}</tbody></table></div>}</div></main>;
}
