import Link from 'next/link';
import { scenarioCards, services, site } from '@/content/site';
import { BadgePill, CapabilityPill, CTAButton, PremiumCard, SectionHeader, SectionShell, VisualPanel } from '@/components/ui/primitives';

const productSupplyCards = [
  { title: 'Fiber Optic Systems', examples: ['OM3/OS2 cables', 'ODF & splice trays', 'LC/SC connectivity'] },
  { title: 'CAT6 Copper Cabling', examples: ['CAT6 / CAT6A bulk cable', 'Patch cords', 'Keystone modules'] },
  { title: 'Patch Panels & Connectivity', examples: ['Patch panels', 'RJ45 accessories', 'Termination components'] },
  { title: 'Cabinets / Racks / PDU', examples: ['Network cabinets', 'Rack PDUs', 'UPS battery cabinets'] },
  { title: 'Cable Management', examples: ['Duct systems', 'Cable trunking', 'Routing accessories'] },
  { title: 'CCTV & Security Components', examples: ['Camera connectivity', 'Control-room links', 'Structured camera cabling'] },
];

const lifecycle = [
  { step: '01', title: 'Scope & Site Survey', label: 'Assessment', description: 'Define routing constraints, room requirements, and rollout priorities before execution.' },
  { step: '02', title: 'Product Direction & Supply', label: 'Procurement Alignment', description: 'Map components to project scope, compatibility, and available delivery windows.' },
  { step: '03', title: 'Structured Implementation', label: 'Execution', description: 'Deploy cabling, cabinets, endpoints, and pathway organization with technical discipline.' },
  { step: '04', title: 'Testing & Validation', label: 'Quality Workflow', description: 'Apply Fluke/OTDR-oriented workflows to verify continuity and link performance.' },
  { step: '05', title: 'Handover & Support', label: 'Operational Transition', description: 'Complete handover readiness and support planning for stable business operations.' },
];

const capabilityMatrix = [
  { environment: 'Offices & Commercial Spaces', tags: ['Fiber', 'CAT6', 'Cabinets', 'Testing', 'CCTV', 'RFQ Supply', 'Support'] },
  { environment: 'Data Rooms & Technical Rooms', tags: ['Fiber', 'CAT6', 'Cabinets', 'Testing', 'RFQ Supply', 'Support'] },
  { environment: 'Warehouses & Factories', tags: ['Fiber', 'CAT6', 'Testing', 'CCTV', 'RFQ Supply', 'Support'] },
  { environment: 'CCTV & Security Infrastructure', tags: ['Fiber', 'CAT6', 'Testing', 'CCTV', 'RFQ Supply', 'Support'] },
  { environment: 'Enterprise Expansion Projects', tags: ['Fiber', 'CAT6', 'Cabinets', 'Testing', 'RFQ Supply', 'Support'] },
];

const assuranceCards = [
  { title: 'Scope-Based Recommendations', description: 'Product and service direction is shaped around the project requirement.' },
  { title: 'Availability Confirmation', description: 'Supply requests are confirmed before quotation and delivery planning.' },
  { title: 'Testing-Oriented Handover', description: 'Network quality is treated as part of the delivery process.' },
  { title: 'Transparent Brand References', description: 'Brand ecosystems are referenced without implying formal partnership unless verified.' },
];

export function Hero() {
  return <SectionShell className="bg-navy-900 text-white"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-orange-300">Enterprise Connectivity Infrastructure</p><h1 className="mt-3 text-3xl font-bold leading-[1.15] sm:text-4xl md:text-5xl">{site.positioning}</h1><p className="mt-4 text-sm text-slate-200 sm:text-base md:mt-5 md:text-lg">HILTECH supports structured cabling, fiber optic systems, data room infrastructure, CCTV connectivity, testing workflows, and project-based supply for business environments across Egypt.</p><div className="mt-5 flex flex-wrap gap-2 md:mt-6">{['Structured Cabling', 'Fiber Optic Systems', 'Data Rooms', 'CCTV Connectivity', 'Testing & Validation', 'Project Supply'].map((chip) => <CapabilityPill key={chip}>{chip}</CapabilityPill>)}</div><div className="mt-6 flex flex-col gap-2.5 sm:flex-row sm:flex-wrap md:mt-8"><CTAButton href="/contact">Request a Project Quote</CTAButton><CTAButton href="#capabilities" variant="secondary">Explore Capabilities</CTAButton><CTAButton href="/products-partners" variant="ghost">Build RFQ Basket</CTAButton></div></div><VisualPanel title="Enterprise Physical-Layer Blueprint" description="Strategic coverage from cabling backbone and data room readiness to testing confidence and project supply." labels={['Backbone', 'Data Room', 'Validation', 'Supply']} /></div></SectionShell>;
}

export function PhysicalLayer() { return <SectionShell compact><SectionHeader title="The Physical Infrastructure Layer Behind Reliable Networks" description="Enterprise connectivity depends on more than devices and internet service. It depends on the cabling, fiber routes, racks, cabinets, connectivity components, testing, and documentation that keep systems stable over time." /><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[{ title: 'Cabling Backbone', description: 'Copper and fiber routes built for stable business connectivity.' }, { title: 'Data Room Readiness', description: 'Cabinets, racks, patching, ODFs, PDUs, and organized infrastructure.' }, { title: 'Testing Confidence', description: 'Fluke/OTDR-oriented validation workflows before handover.' }, { title: 'Project Supply', description: 'Infrastructure components selected around scope, availability, and compatibility.' }].map((card) => <PremiumCard key={card.title} className="bg-slate-50"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Physical Layer</p><h3 className="mt-2 font-semibold text-slate-900">{card.title}</h3><p className="mt-2 text-sm text-slate-600">{card.description}</p></PremiumCard>)}</div></SectionShell>; }

export function ConnectivityLifecycle() { return <SectionShell><SectionHeader title="From Requirement to Reliable Operation" description="An operating model that connects planning, supply, implementation, validation, and operational continuity." /><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{lifecycle.map((item) => <PremiumCard key={item.step}><p className="text-xs font-semibold tracking-widest text-orange-600">STEP {item.step}</p><h3 className="mt-2 font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{item.label}</p><p className="mt-2 text-sm text-slate-600">{item.description}</p></PremiumCard>)}</div></SectionShell>; }

export function ServicesGrid() { return <SectionShell><SectionHeader title="Core Infrastructure Services" description="Services designed around the physical network layer — from structured cabling and fiber installation to testing, cabinets, security infrastructure, and ongoing support." /><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map((s) => <PremiumCard key={s.title} accent className="group flex h-full flex-col"><BadgePill>{s.label}</BadgePill><h3 className="mt-2 font-semibold text-slate-900">{s.title}</h3><p className="mt-2 text-sm text-slate-600">{s.description}</p><p className="mt-3 text-xs text-slate-500">Technical scope • Procurement-aware • Enterprise-ready</p></PremiumCard>)}</div></SectionShell>; }

export function CapabilityMatrix() { return <SectionShell className="bg-slate-50"><div id="capabilities"><SectionHeader title="Capabilities Across Project Environments" description="Delivery scope mapped by environment so project teams can align technical priorities quickly." /><div className="mt-8 grid gap-4">{capabilityMatrix.map((row) => <PremiumCard key={row.environment} className="bg-white"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><h3 className="font-semibold text-slate-900">{row.environment}</h3><div className="flex flex-wrap gap-2">{row.tags.map((tag) => <CapabilityPill key={`${row.environment}-${tag}`}>{tag}</CapabilityPill>)}</div></div></PremiumCard>)}</div></div></SectionShell>; }

export function ProductsSupply() { return <SectionShell className="bg-white"><SectionHeader title="Products & Project Supply" description="Build a project-ready supply list for cables, cabinets, patching components, fiber accessories, CCTV connectivity, and infrastructure parts — then send it to HILTECH for availability and quotation." /><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{productSupplyCards.map((item) => <PremiumCard key={item.title} className="bg-slate-50"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-orange-600">Project Supply</p><p className="font-semibold text-slate-900">{item.title}</p><ul className="mt-2 space-y-1 text-sm text-slate-600">{item.examples.map((example) => <li key={example}>• {example}</li>)}</ul></PremiumCard>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><CTAButton href="/products-partners">View Products & Project Supply</CTAButton><CTAButton href="/products-partners" variant="secondary">Build RFQ Basket</CTAButton></div></SectionShell>; }

export function ProjectScenarios() { return <SectionShell><SectionHeader title="Project Scenarios We Support" /><div className="mt-7 grid gap-4 md:mt-8 md:grid-cols-2">{scenarioCards.map((scenario) => <PremiumCard key={scenario.title}><div className="mb-3 flex items-center gap-2"><span className="h-1 w-8 rounded-full bg-orange-400" /><p className="text-[11px] font-semibold uppercase tracking-wide text-orange-600">Scenario</p></div><h3 className="text-lg font-semibold">{scenario.title}</h3><p className="mt-2 text-sm text-slate-600">{scenario.description}</p></PremiumCard>)}</div></SectionShell>; }

export function EnterpriseAssurance() { return <SectionShell><SectionHeader title="Built for Clear, Confirmable Delivery" /><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{assuranceCards.map((card) => <PremiumCard key={card.title}><h3 className="font-semibold text-slate-900">{card.title}</h3><p className="mt-2 text-sm text-slate-600">{card.description}</p></PremiumCard>)}</div></SectionShell>; }

export function RFQEntryPoint() { return <SectionShell className="bg-navy-800 text-white"><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div><SectionHeader title="Turn Project Requirements into an RFQ List" description="Select infrastructure products, define quantities, add notes, and send a structured RFQ request directly to HILTECH through WhatsApp." className="text-white [&>h2]:text-white [&>p]:text-slate-200" /><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><CTAButton href="/products-partners">Browse Products</CTAButton><CTAButton href="/products-partners" variant="secondary">Open RFQ Basket</CTAButton><CTAButton href="/contact" variant="ghost">Request Project Quote</CTAButton></div></div><PremiumCard className="border-slate-700 bg-navy-900/50 text-slate-100"><p className="text-xs font-semibold uppercase tracking-wide text-orange-300">RFQ Workflow</p><p className="mt-2 text-sm">Build item list → define quantity → add notes → share instantly on WhatsApp for quotation handling.</p><Link href={site.contact.whatsappRFQLink} className="mt-4 inline-flex text-sm font-semibold text-orange-300 underline underline-offset-4">Start RFQ Message</Link></PremiumCard></div></SectionShell>; }
