'use client';

import Image from 'next/image';
import Link from 'next/link';
import { CTAButton, PremiumCard, SectionHeader, SectionShell } from '@/components/ui/primitives';
import { trackEvent } from '@/lib/client/analytics';
import { site } from '@/content/site';

const trustStripItems = ['Egypt-based delivery','Structured cabling','Fiber optics','Rack preparation','Testing before handover','RFQ tracking','WhatsApp coordination'];
const deliverables = [
  { title: 'Structured Cabling', description: 'CAT6/CAT6A routes, outlets, patching, and labeling for business facilities.' },
  { title: 'Fiber Optic Infrastructure', description: 'Fiber routes, termination, ODF preparation, and testing-ready handover.' },
  { title: 'Racks & Data Rooms', description: 'Rack preparation, cable management, patch panels, PDUs, and maintainable layout.' },
  { title: 'Testing & Handover', description: 'Validation-focused checks before handover with clear scope notes.' },
];
const projectScopeCards = [
  { title: 'Office Network Setup', includes: ['CAT6 cabling', 'patch panel', 'faceplates', 'rack accessories', 'testing'] },
  { title: 'Rack Room Preparation', includes: ['rack', 'PDU', 'cable management', 'patch panels', 'labeling/testing'] },
  { title: 'Fiber Backbone Scope', includes: ['fiber cable', 'ODF', 'patch cords', 'splicing/testing'] },
  { title: 'CCTV Infrastructure Scope', includes: ['network points', 'cabling', 'rack preparation', 'power/network readiness'] },
];

export function Hero() { return <SectionShell className="overflow-x-clip bg-gradient-to-br from-navy-900 via-navy-900 to-slate-900 py-10 text-white sm:py-14 md:py-20"><div className="grid items-center gap-6 lg:grid-cols-[1.05fr_0.95fr] lg:gap-8"><div className="max-w-3xl"><p className="public-eyebrow text-orange-300 sm:text-sm">NETWORK INFRASTRUCTURE IN EGYPT</p><h1 className="mt-3 text-3xl font-bold leading-[1.15] sm:text-4xl md:text-5xl">Reliable Network Infrastructure for Offices, Data Rooms & Business Sites in Egypt</h1><p className="mt-4 max-w-2xl text-sm text-slate-100 sm:text-base">HILTECH helps companies plan, source, install, and test structured cabling, fiber optics, racks, CCTV infrastructure, and project-ready RFQ packages.</p><div className="mt-6 flex flex-col gap-2.5 sm:flex-row sm:flex-wrap sm:gap-3"><CTAButton href="/rfq" className="w-full justify-center sm:w-auto" onClick={() => trackEvent('hero_rfq_click', { source: 'home_hero' })}>Request Project Quote</CTAButton><CTAButton href="/products-partners" variant="secondary" className="w-full justify-center sm:w-auto">Browse Products</CTAButton><CTAButton href="/work" variant="secondary" className="w-full justify-center sm:w-auto">View Field Work</CTAButton></div></div><PremiumCard className="h-fit self-center overflow-hidden border-white/10 bg-white/5 p-0 backdrop-blur-sm"><div className="relative aspect-[4/3] w-full"><Image src="/rack-front-cabling.jpg" alt="Network rack and data room preparation for project handover" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 40vw" priority /></div><div className="p-4"><p className="public-eyebrow text-orange-200">Field proof</p><div className="mt-2 flex flex-wrap gap-2">{['Structured cabling', 'Fiber / ODF', 'Rack preparation', 'Testing before handover'].map((tag) => (<span key={tag} className="rounded-full border border-white/20 bg-white/10 px-2.5 py-1 text-xs font-semibold text-white">{tag}</span>))}</div></div></PremiumCard></div></SectionShell>; }

export function ProofMetricsStrip() { return <SectionShell compact><div className="mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[['24/7','Technical Support'],['+1000','Products Supplied'],['+500','Projects Delivered'],['+10','Years of Experience']].map(([value,label])=><div key={label} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-center"><p className="text-lg font-bold text-navy-900">{value}</p><p className="text-xs font-semibold text-slate-600">{label}</p></div>)}</div></div></SectionShell>; }
export function TrustStrip() { return <SectionShell compact><div className="mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:p-4"><ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{trustStripItems.map((item)=><li key={item} className="public-marker justify-center text-center sm:text-sm">{item}</li>)}</ul></div></SectionShell>; }
export function WhatHiltechDoes() { return <SectionShell compact><SectionHeader eyebrow="What HILTECH Delivers" title="Infrastructure scope built for business facilities" description="Offices, factories, data rooms, and commercial sites." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{deliverables.map((card)=><PremiumCard key={card.title} className="bg-white p-4"><h3 className="font-semibold text-slate-900">{card.title}</h3><p className="mt-1.5 text-sm text-slate-700">{card.description}</p></PremiumCard>)}</div></SectionShell>; }
export function ProjectScopeSection() { return <SectionShell compact><SectionHeader title="Build a Complete Project Scope" description="Plan complete RFQ-ready scope starters for offices, rack rooms, fiber backbone, and CCTV infrastructure." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{projectScopeCards.map((card)=><PremiumCard key={card.title} className="bg-white p-4"><h3 className="font-semibold text-slate-900">{card.title}</h3><ul className="mt-2 space-y-1 text-sm text-slate-700">{card.includes.map((line)=><li key={line}>• {line}</li>)}</ul><Link href="/rfq" className="mt-3 inline-block text-sm font-semibold text-orange-700 hover:underline">Start RFQ with this scope</Link></PremiumCard>)}</div></SectionShell>; }
export function ProductCategoriesPreview() { const cats = [
  ['Fiber Optics','Fiber cables, ODFs, connectors, and accessories for backbone projects.','Fiber Optic Systems'],
  ['Structured Cabling','CAT6/CAT6A infrastructure components for office and facility networks.','Copper / CAT6 Cabling'],
  ['Racks & Cabinets','Cabinets, rack accessories, cable management, and power preparation.','Cabinets / Racks / PDU'],
  ['Patch Panels & Connectivity','Patch panels, keystones, couplers, and connectivity accessories.','Patch Cords & Connectivity'],
  ['CCTV Infrastructure','Camera cabling, network accessories, and control-room readiness items.','CCTV & Security'],
  ['Testing Tools','Field testing references for fiber and copper validation workflows.',null],
  ['Power & Rack Accessories','PDU, UPS references, and structured power accessories for racks.','Cabinets / Racks / PDU'],
  ['Project Supply','Project-based product supply across coordinated network requirements.','/rfq'],
] as const; return <SectionShell compact><SectionHeader title="Browse products and build one RFQ basket for the full project scope." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cats.map(([title,desc,mappedCategory])=><PremiumCard key={title} className="bg-white p-4"><h3 className="font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-700">{desc}</p><Link href={mappedCategory === '/rfq' ? '/rfq' : mappedCategory ? `/products-partners?category=${encodeURIComponent(mappedCategory)}` : title === 'Testing Tools' ? '/work' : '/products-partners'} className="mt-2 inline-block text-sm font-semibold text-orange-700">{mappedCategory === '/rfq' ? 'Start RFQ' : 'View Category'}</Link></PremiumCard>)}</div><div className="mt-5 flex flex-col gap-2.5 sm:flex-row"><CTAButton href="/products-partners" variant="secondary" className="w-full justify-center sm:w-auto">Browse Products</CTAButton><CTAButton href="/rfq" className="w-full justify-center sm:w-auto">Request Quote</CTAButton></div></SectionShell>; }
export function FieldWorkPreview() { return <SectionShell className="bg-slate-50"><SectionHeader title="Field work built for reliable handover" description="Real HILTECH field snapshots that support trust before quotation." /><div className="mt-5 grid gap-3 sm:grid-cols-3">{[{title:'Rack & data room preparation',image:'/rack-front-cabling.jpg',note:'Scope note: layout, patching flow, and maintainable routing.'},{title:'Fiber / ODF work',image:'/fiber-splicing-workbench.jpg',note:'Scope note: backbone readiness and termination context.'},{title:'Structured cabling and testing',image:'/testing-otdr-device.jpg',note:'Confidence note: validation before handover.'}].map((item)=><PremiumCard key={item.title} className="overflow-hidden bg-white p-0"><div className="relative aspect-[16/10] w-full"><Image src={item.image} alt={item.title} fill className="object-cover" /></div><div className="p-3.5"><h3 className="font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-sm text-slate-700">{item.note}</p><Link href="/work" className="mt-2 inline-block text-sm font-semibold text-orange-700">View field work</Link></div></PremiumCard>)}</div></SectionShell>; }
export function RFQProcessSection() { return <SectionShell compact><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><SectionHeader eyebrow="RFQ Process" title="Clear request flow from scope to quote" description="Keep technical scope, item needs, and contact details in one request." /><div className="mt-4 grid gap-2.5 md:grid-cols-3">{['Select products','Add quantities','Submit & track'].map((s,i)=><PremiumCard key={s} className="bg-slate-50 p-4"><p className="public-eyebrow text-orange-600">Step {i+1}</p><p className="mt-1 font-semibold text-slate-900">{s}</p></PremiumCard>)}</div><div className="mt-5 flex flex-col gap-2.5 sm:flex-row"><CTAButton href="/rfq" className="w-full justify-center sm:w-auto">Request Project Quote</CTAButton><CTAButton href="/track" variant="secondary" className="w-full justify-center sm:w-auto">Track Existing RFQ</CTAButton></div></section></SectionShell>; }
export function WhyChooseHiltechSection() { return <SectionShell compact><SectionHeader eyebrow="Why choose HILTECH" title="Built for practical project delivery" description="A compact operating model focused on RFQ clarity, field execution, and aligned product references." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['RFQ-first workflow','Submit products and scope in one structured request.'],['Field-aware delivery','Planning considers routing, racks, testing, and handover.'],['Clear communication','Follow up by phone, WhatsApp, or tracking reference.'],['Practical product alignment','References align with actual project needs before quotation.']].map(([t,d])=><PremiumCard key={t} className="bg-white p-4"><h3 className="font-semibold text-slate-900">{t}</h3><p className="mt-1 text-sm text-slate-700">{d}</p></PremiumCard>)}</div></SectionShell>; }
export function ProductReferencesPanel() { return <SectionShell compact><section className="mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><SectionHeader eyebrow="Product References" title="Compatible Product References" description="Brand and product references used for project catalog context." /><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="relative mx-auto h-32 w-full max-w-4xl sm:h-40"><Image src="/ch-product-references.jpeg" alt="Compatible product references panel" fill className="object-contain" /></div></div><p className="mt-3 text-xs text-slate-500">Product references are shown for catalog/context purposes only and do not imply formal partnership unless explicitly stated.</p></section></SectionShell>; }
export function ContactConfidenceSection() { return <SectionShell compact><section className="mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 className="text-2xl font-bold text-slate-900">Need help defining your network scope?</h2><ul className="mt-4 grid gap-2 text-sm text-slate-700 sm:grid-cols-2"><li><span className="font-semibold">Call:</span> {site.contact.phone}</li><li><span className="font-semibold">WhatsApp / RFQ:</span> 01555357807</li><li><span className="font-semibold">Location:</span> Cairo, Egypt</li><li><span className="font-semibold">Email:</span> {site.contact.email}</li></ul><div className="mt-5 flex flex-col gap-2.5 sm:flex-row"><CTAButton href="/rfq" className="w-full justify-center sm:w-auto">Request Project Quote</CTAButton><CTAButton href="/contact" variant="secondary" className="w-full justify-center sm:w-auto">Contact HILTECH</CTAButton></div></section></SectionShell>; }
export function ServicesGrid() { const services=[['Site Survey','On-site review of routes, rooms, and infrastructure constraints.'],['Fiber Installation','Fiber routing, termination, and splicing preparation for project scope.'],['Structured Cabling','CAT6/CAT6A endpoint distribution and organized patching workflows.'],['Rack & Data Room Setup','Rack layout, patch panel preparation, cable management, and PDUs.'],['CCTV Infrastructure Readiness','Camera cabling paths and control-room network connectivity setup.'],['Testing & Measurement','OTDR, copper, and signal checks before handover where required.'],['Project Product Supply','Project-based product supply aligned with approved technical scope.'],['Maintenance Support','Post-handover support for stable operation and continuity.']]; return <SectionShell compact><SectionHeader title="Core Network Infrastructure Services" description="Practical service capabilities from survey to handover support." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map(([title,description])=><PremiumCard key={title} className="bg-white p-4"><h3 className="text-sm font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-700">{description}</p></PremiumCard>)}</div></SectionShell>; }
export function FinalCTA() { return <SectionShell className="bg-navy-800 py-10 text-white"><SectionHeader title="Ready to price your network infrastructure project?" description="Send products, quantities, BOQ notes, or site requirements and HILTECH will review the scope for quotation follow-up." className="text-white [&>h2]:text-white [&>p]:text-slate-100" /><div className="mt-5 flex flex-col gap-2.5 sm:flex-row"><CTAButton href="/rfq" className="w-full justify-center sm:w-auto">Request Project Quote</CTAButton><a href={site.contact.whatsappGeneralLink} className="inline-flex w-full items-center justify-center rounded-md border border-white/35 px-4 py-2.5 text-sm font-semibold text-white sm:w-auto">Contact on WhatsApp</a></div></SectionShell>; }
