import type { Metadata } from 'next';
import Link from 'next/link';
import AdminShell from '@/components/admin/AdminShell';
import { requireAdminSession } from '@/lib/server/admin-auth';
import { isAdminReportsBackendConfigured, parseReportRange } from '@/lib/server/admin-reports';
export const dynamic = 'force-dynamic'; export const revalidate = 0; export const metadata: Metadata = { title: 'Reports & Export Center', robots: { index: false, follow: false } };
const REPORTS = [{ key: 'rfqs', name: 'RFQ Report', description: 'RFQ operations and quotation workflow columns safe for internal exports.' },{ key: 'sales', name: 'Sales Report', description: 'RFQ quotation totals and pipeline fields using the same grand total formula as sales dashboard.' },{ key: 'product_demand', name: 'Product Demand Report', description: 'Demand rollups by requested item/product, category, brand, and stock matching state.' },{ key: 'inventory_attention', name: 'Inventory Attention Report', description: 'Products requiring inventory attention (low/out/backorder/unknown stock statuses).' },{ key: 'actions', name: 'Actions Report', description: 'Operational action queue snapshot from Action Center safe fields only.' }] as const;
export default async function AdminReportsPage({ searchParams }: { searchParams: Promise<{ range?: string }> }) { await requireAdminSession(); const resolved = await searchParams; const range = parseReportRange(resolved.range); if (!isAdminReportsBackendConfigured()) return <main className="section"><div className="container"><p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-amber-700">Reports backend is not configured.</p></div></main>;
return <AdminShell title='Reports & Export Center' description='Admin-only operational CSV exports for RFQ, sales, products, inventory, and action workflows.'><section className='rounded-xl border border-slate-200 bg-white p-4'><p className='text-sm text-slate-600'>Choose report and date range, then download a safe CSV export.</p></section><section className='grid gap-4 md:grid-cols-2'>{REPORTS.map((report) => <article key={report.key} className='rounded-xl border border-slate-200 bg-white p-4'><h2 className='text-lg font-semibold'>{report.name}</h2><p className='mt-1 text-sm text-slate-600'>{report.description}</p><div className='mt-3 flex flex-wrap gap-2'>{[7,30,90,365].map((r)=><Link key={r} href={`/admin/reports?range=${r}`} className={`rounded border px-3 py-1 text-sm ${range===r?'bg-navy-900 text-white':'border-slate-300'}`}>{r}d</Link>)}</div><div className='mt-4'><Link href={`/api/admin/reports/export?report=${report.key}&range=${range}`} className='rounded-md bg-navy-900 px-3 py-2 text-sm font-semibold text-white'>Download CSV</Link></div></article>)}</section></AdminShell>; }
