import type { Metadata } from 'next';
import Link from 'next/link';
import { SectionShell, PremiumCard, CTAButton, SectionHeader } from '@/components/ui/primitives';
import { solutions } from '@/content/solutions';
import { site } from '@/content/site';

export const metadata: Metadata = {
  title: 'Enterprise Infrastructure Solutions | HILTECH',
  description: 'Explore HILTECH solutions for structured cabling, fiber backbone, data rooms, CCTV infrastructure, network testing, and project-based supply.',
  alternates: { canonical: `${site.siteUrl}/solutions` },
  openGraph: { title: 'Enterprise Infrastructure Solutions | HILTECH', description: 'Enterprise-grade infrastructure solution pathways for business environments.', url: `${site.siteUrl}/solutions`, images: [site.ogImage] },
  twitter: { card: 'summary_large_image', images: [site.ogImage] },
};

export default function SolutionsPage() {
  return <main><SectionShell><section className="rounded-2xl border border-navy-900/20 bg-gradient-to-br from-navy-900 to-slate-900 p-6 text-white md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-300">Enterprise Infrastructure Solutions</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Enterprise Infrastructure Solutions</h1><p className="mt-3 max-w-4xl text-sm text-slate-200 md:text-base">Explore HILTECH solutions for structured cabling, fiber backbone, data rooms, CCTV infrastructure, network testing, and project-based supply.</p></section><section className="mt-8"><SectionHeader title="Solution Pathways" description="Solution pages are organized around infrastructure outcomes and implementation readiness." /><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{solutions.map((solution) => <PremiumCard key={solution.slug} className="flex h-full flex-col"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">{solution.eyebrow}</p><h2 className="mt-2 text-lg font-bold text-slate-900">{solution.shortTitle}</h2><p className="mt-2 text-sm text-slate-600">{solution.intro}</p><div className="mt-4"><Link className="text-sm font-semibold text-navy-900 underline underline-offset-4" href={`/solutions/${solution.slug}`}>View solution details</Link></div></PremiumCard>)}</div></section><section className="mt-10 rounded-2xl border border-slate-200 bg-slate-50 p-5 md:p-6"><h2 className="text-2xl font-bold text-slate-900">How HILTECH approaches infrastructure delivery</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{['Scope-first planning and constraints review', 'Compatibility and availability confirmation before quotation', 'Testing-oriented validation and handover readiness'].map((item) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-medium text-slate-700">{item}</div>)}</div></section><section className="mt-10 rounded-2xl border border-slate-200 bg-white p-5 md:p-6"><h2 className="text-xl font-bold text-slate-900">Next step for your project</h2><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><CTAButton href="/rfq">Review RFQ Basket</CTAButton><CTAButton href="/products-partners" variant="secondary">Browse Products & Partners</CTAButton><CTAButton href="/contact" variant="ghost">Request Project Quote</CTAButton></div><p className="mt-4 text-xs text-slate-500">Final scope, availability, and technical requirements are confirmed per project.</p></section></SectionShell></main>;
}
