-- Seed products from static catalog content (Phase 25C.1)
INSERT INTO public.products (
  product_code,
  name,
  slug,
  category,
  category_slug,
  brand,
  short_specs,
  use_case,
  image_path,
  status,
  sort_order,
  is_featured,
  source
)
VALUES
(
  'fiber-leviton-om3',
  'Leviton OM3 Fiber Cable',
  'fiber-leviton-om3',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Leviton',
  'OM3 multimode fiber backbone cable.',
  'Campus and enterprise backbone connectivity.',
  '/products/fiber-leviton-om3.png',
  'active',
  1,
  false,
  'seed_static'
),
(
  'fiber-om3-12-core',
  'OM3 Multimode 12 Core Fiber Cable',
  'fiber-om3-12-core',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  '12-core OM3 multimode configuration.',
  'Inter-floor and data room uplinks.',
  '/products/fiber-om3-12-core.png',
  'active',
  2,
  false,
  'seed_static'
),
(
  'fiber-armored-outdoor',
  'Outdoor Armored Fiber Cable',
  'fiber-armored-outdoor',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'Outdoor-rated armored protection for harsh paths.',
  'External runs and high-risk cable routes.',
  '/products/fiber-armored-outdoor.png',
  'active',
  3,
  false,
  'seed_static'
),
(
  'fiber-odf',
  'ODF Optical Distribution Frame',
  'fiber-odf',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'Fiber termination and management frame.',
  'Centralized fiber distribution in comms rooms.',
  '/products/fiber-odf.png',
  'active',
  4,
  false,
  'seed_static'
),
(
  'fiber-panel-24p',
  'Fiber Patch Panel 24P',
  'fiber-panel-24p',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  '24-port fiber panel for rack mounting.',
  'High-density patching and neat terminations.',
  '/products/fiber-panel-24p.png',
  'active',
  5,
  false,
  'seed_static'
),
(
  'fiber-splice-trays',
  'Splice Trays',
  'fiber-splice-trays',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'Organized splice protection and retention.',
  'Fiber splice workflows and maintenance.',
  '/products/fiber-splice-trays.png',
  'active',
  6,
  false,
  'seed_static'
),
(
  'fiber-lc-sc-connectors',
  'LC / SC Connectors',
  'fiber-lc-sc-connectors',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'LC and SC termination interface options.',
  'Terminating patch panels and end points.',
  '/products/fiber-lc-sc-connectors.png',
  'active',
  7,
  false,
  'seed_static'
),
(
  'fiber-pigtail-lc-sc',
  'Pigtail LC / SC',
  'fiber-pigtail-lc-sc',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'Factory-polished pigtails for splicing.',
  'Fast and clean fiber terminations.',
  '/products/fiber-pigtail-lc-sc.png',
  'active',
  8,
  false,
  'seed_static'
),
(
  'fiber-coupler-lc-sc',
  'Coupler LC / SC',
  'fiber-coupler-lc-sc',
  'Fiber Optic Systems',
  'fiber-optic-systems',
  'Generic / Multi-brand',
  'LC/SC couplers for duplex/simplex continuity.',
  'Patch panel and enclosure connection points.',
  '/products/fiber-coupler-lc-sc.png',
  'active',
  9,
  false,
  'seed_static'
),
(
  'patch-fiber-lclc-om3',
  'Fiber Patch Cord LC/LC OM3',
  'patch-fiber-lclc-om3',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'Generic / Multi-brand',
  'LC-LC duplex OM3 patch lead.',
  'In-rack fiber patching.',
  '/products/patch-fiber-lclc-om3.png',
  'active',
  10,
  false,
  'seed_static'
),
(
  'patch-fiber-lclc-os2',
  'Fiber Patch Cord LC/LC Single Mode OS2',
  'patch-fiber-lclc-os2',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'Generic / Multi-brand',
  'OS2 single-mode LC-LC patch cord.',
  'Long-distance or single-mode links.',
  '/products/patch-fiber-lclc-os2.png',
  'active',
  11,
  false,
  'seed_static'
),
(
  'patch-hpe-flex-om4',
  'HPE Premier Flex LC/LC Multi-mode OM4',
  'patch-hpe-flex-om4',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'HPE',
  'OM4 multimode LC-LC enterprise patching.',
  'Core switch and server interconnects.',
  '/products/patch-hpe-flex-om4.png',
  'active',
  12,
  false,
  'seed_static'
),
(
  'patch-commscope-lclc',
  'CommScope LC to LC Duplex Zipcord',
  'patch-commscope-lclc',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'CommScope',
  'Duplex zipcord LC-LC assembly.',
  'Structured fiber patching in cabinets.',
  '/products/patch-commscope-lclc.png',
  'active',
  13,
  false,
  'seed_static'
),
(
  'patch-lclc-3m',
  'Patch Cord LC/LC 3 Meter',
  'patch-lclc-3m',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'Generic / Multi-brand',
  '3m LC-LC patch length option.',
  'Cross-connect and equipment linking.',
  '/products/patch-lclc-3m.png',
  'active',
  14,
  false,
  'seed_static'
),
(
  'patch-lcsc',
  'Patch Cord LC/SC',
  'patch-lcsc',
  'Patch Cords & Connectivity',
  'patch-cords-connectivity',
  'Generic / Multi-brand',
  'Mixed interface LC-SC patch option.',
  'Hybrid patching requirements.',
  '/products/patch-lcsc.png',
  'active',
  15,
  false,
  'seed_static'
),
(
  'copper-legrand-cat6',
  'Legrand CAT6 U/UTP LSZH Cable 305M',
  'copper-legrand-cat6',
  'Copper / CAT6 Cabling',
  'copper-cat6-cabling',
  'Legrand',
  '305m box, CAT6 U/UTP, LSZH sheath.',
  'Horizontal office cabling.',
  '/products/copper-legrand-cat6.png',
  'active',
  16,
  false,
  'seed_static'
),
(
  'copper-leviton-cat6',
  'Leviton CAT6 LSZH Network Cable 305M',
  'copper-leviton-cat6',
  'Copper / CAT6 Cabling',
  'copper-cat6-cabling',
  'Leviton',
  'CAT6 LSZH network cable in 305m length.',
  'Enterprise floor cabling projects.',
  '/products/copper-leviton-cat6.png',
  'active',
  17,
  false,
  'seed_static'
),
(
  'copper-panduit-cat6a',
  'Panduit Category 6A U/UTP Copper Cable 305M',
  'copper-panduit-cat6a',
  'Copper / CAT6 Cabling',
  'copper-cat6-cabling',
  'Panduit',
  'CAT6A U/UTP for higher throughput needs.',
  '10G-ready structured cabling layouts.',
  '/products/copper-panduit-cat6a.png',
  'active',
  18,
  false,
  'seed_static'
),
(
  'copper-cat6-patch',
  'CAT6 UTP Patch Cord',
  'copper-cat6-patch',
  'Copper / CAT6 Cabling',
  'copper-cat6-cabling',
  'Generic / Multi-brand',
  'UTP CAT6 patch lead variations.',
  'Workstation and patch panel connections.',
  '/products/copper-cat6-patch.png',
  'active',
  19,
  false,
  'seed_static'
),
(
  'copper-cat6a-patch',
  'CAT6A Patch Cord',
  'copper-cat6a-patch',
  'Copper / CAT6 Cabling',
  'copper-cat6-cabling',
  'Generic / Multi-brand',
  'CAT6A patching for high bandwidth links.',
  'High-performance switch-to-device links.',
  '/products/copper-cat6a-patch.png',
  'active',
  20,
  false,
  'seed_static'
),
(
  'fp-legrand-rj45',
  'Legrand RJ45 Socket Category 6 UTP',
  'fp-legrand-rj45',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Legrand',
  'CAT6 UTP RJ45 outlet component.',
  'User outlet and wall point terminations.',
  '/products/fp-legrand-rj45.png',
  'active',
  21,
  false,
  'seed_static'
),
(
  'fp-excel-keystone',
  'Excel CAT6 UTP Keystone Jack',
  'fp-excel-keystone',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Excel',
  'Tool-compatible CAT6 keystone module.',
  'Patch panel and faceplate integration.',
  '/products/fp-excel-keystone.png',
  'active',
  22,
  false,
  'seed_static'
),
(
  'fp-surface-back-box',
  'Surface Mount Back Box',
  'fp-surface-back-box',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Generic / Multi-brand',
  'Surface-mount enclosure for outlets.',
  'Retrofit locations without flush box.',
  '/products/fp-surface-back-box.png',
  'active',
  23,
  false,
  'seed_static'
),
(
  'fp-single-faceplate',
  'Single Gang Faceplate',
  'fp-single-faceplate',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Generic / Multi-brand',
  'Single-gang front plate for keystone inserts.',
  'Neat and standardized outlet finish.',
  '/products/fp-single-faceplate.png',
  'active',
  24,
  false,
  'seed_static'
),
(
  'fp-rj45-box',
  'RJ45 Connector Box',
  'fp-rj45-box',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Generic / Multi-brand',
  'Housing for RJ45 outlet assemblies.',
  'Endpoint termination and labeling.',
  '/products/fp-rj45-box.png',
  'active',
  25,
  false,
  'seed_static'
),
(
  'fp-field-plug',
  'Field Termination Plug',
  'fp-field-plug',
  'Faceplates / Keystone / RJ45',
  'faceplates-keystone-rj45',
  'Generic / Multi-brand',
  'On-site terminated RJ45 plug component.',
  'Custom cable lengths and fast fixes.',
  '/products/fp-field-plug.png',
  'active',
  26,
  false,
  'seed_static'
),
(
  'rack-network-cabinets',
  'Network Cabinets',
  'rack-network-cabinets',
  'Cabinets / Racks / PDU',
  'cabinets-racks-pdu',
  'Generic / Multi-brand',
  '19-inch network cabinet formats.',
  'Core comms room and edge cabinet deployment.',
  '/products/rack-network-cabinets.png',
  'active',
  27,
  false,
  'seed_static'
),
(
  'rack-ups-cabinets',
  'UPS Battery Cabinets',
  'rack-ups-cabinets',
  'Cabinets / Racks / PDU',
  'cabinets-racks-pdu',
  'Generic / Multi-brand',
  'Battery cabinet housing for UPS ecosystems.',
  'Power continuity and backup planning.',
  '/products/rack-ups-cabinets.png',
  'active',
  28,
  false,
  'seed_static'
),
(
  'rack-apc-schneider-ups',
  'APC / Schneider-style UPS Battery Cabinets',
  'rack-apc-schneider-ups',
  'Cabinets / Racks / PDU',
  'cabinets-racks-pdu',
  'APC / Schneider Electric style',
  'Form factors aligned with enterprise UPS environments.',
  'Data room power infrastructure expansion.',
  '/products/rack-apc-schneider-ups.png',
  'active',
  29,
  false,
  'seed_static'
),
(
  'rack-19in-pdu',
  '19 Inch Rack PDU',
  'rack-19in-pdu',
  'Cabinets / Racks / PDU',
  'cabinets-racks-pdu',
  'Generic / Multi-brand',
  '19-inch rack power distribution unit.',
  'Organized in-rack power delivery.',
  '/products/rack-19in-pdu.png',
  'active',
  30,
  false,
  'seed_static'
),
(
  'rack-accessories',
  'Rack Accessories',
  'rack-accessories',
  'Cabinets / Racks / PDU',
  'cabinets-racks-pdu',
  'Generic / Multi-brand',
  'Shelves, blanks, cable rings, and mounting kits.',
  'Clean and scalable rack finishing.',
  '/products/rack-accessories.png',
  'active',
  31,
  false,
  'seed_static'
),
(
  'cable-legrand-duct',
  'Legrand PVC Decorative Duct',
  'cable-legrand-duct',
  'Cable Management / Duct Systems',
  'cable-management-duct-systems',
  'Legrand',
  'Decorative PVC trunking profile.',
  'Visible office routes with neat finish.',
  '/products/cable-legrand-duct.png',
  'active',
  32,
  false,
  'seed_static'
),
(
  'cable-trunking',
  'Cable Trunking',
  'cable-trunking',
  'Cable Management / Duct Systems',
  'cable-management-duct-systems',
  'Generic / Multi-brand',
  'Cable routing channels and covers.',
  'Protected pathway for network and power runs.',
  '/products/cable-trunking.png',
  'active',
  33,
  false,
  'seed_static'
),
(
  'cable-routing-acc',
  'Cable Routing Accessories',
  'cable-routing-acc',
  'Cable Management / Duct Systems',
  'cable-management-duct-systems',
  'Generic / Multi-brand',
  'Corners, joints, separators, and route supports.',
  'Complete duct system continuity.',
  '/products/cable-routing-acc.png',
  'active',
  34,
  false,
  'seed_static'
),
(
  'cctv-hikvision-cams',
  'Hikvision Network Cameras',
  'cctv-hikvision-cams',
  'CCTV & Security',
  'cctv-security',
  'Hikvision',
  'IP camera product lines for surveillance.',
  'Office, campus, and facility monitoring.',
  '/products/cctv-hikvision-cams.png',
  'active',
  35,
  false,
  'seed_static'
),
(
  'cctv-connectivity',
  'CCTV Connectivity',
  'cctv-connectivity',
  'CCTV & Security',
  'cctv-security',
  'Generic / Multi-brand',
  'Patch, connectors, and endpoint links for CCTV.',
  'Reliable camera network communication.',
  '/products/cctv-connectivity.png',
  'active',
  36,
  false,
  'seed_static'
),
(
  'cctv-cabling',
  'Camera Cabling',
  'cctv-cabling',
  'CCTV & Security',
  'cctv-security',
  'Generic / Multi-brand',
  'Structured paths for camera power/data.',
  'End-to-end surveillance installation readiness.',
  '/products/cctv-cabling.png',
  'active',
  37,
  false,
  'seed_static'
),
(
  'cctv-control-room',
  'Control-room Readiness',
  'cctv-control-room',
  'CCTV & Security',
  'cctv-security',
  'Generic / Multi-brand',
  'Infrastructure essentials for monitoring spaces.',
  'Security operation center preparation.',
  '/products/cctv-control-room.png',
  'active',
  38,
  false,
  'seed_static'
)
ON CONFLICT (product_code) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  category = EXCLUDED.category,
  category_slug = EXCLUDED.category_slug,
  brand = EXCLUDED.brand,
  short_specs = EXCLUDED.short_specs,
  use_case = EXCLUDED.use_case,
  image_path = EXCLUDED.image_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  is_featured = EXCLUDED.is_featured,
  source = EXCLUDED.source,
  updated_at = now();
